### ISSUE TITLE
Subtypes of serializable types are not serializable

### ISSUE THREAD

**Issue by konstin** [ijl/orjson#1]
```python
import json
import orjson

class MyDict(dict):
    pass

my_dict = MyDict({"id": 1})
json.dumps(my_dict) # works
orjson.dumps(my_dict) # fails
```

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Type is not JSON serializable: MyDict
```

**Comment by ijl** [comment]
Is it significant for a use you have to support subclasses?

**Comment by ijl** [comment]
Ok. I don't intend it as a drop-in replacement, and have added a note to that effect. I think though that accepting subclasses of dict and instances of defaultdict and OrderedDict would be reasonable.

**Comment by konstin** [comment]
Ah ok
