### ISSUE TITLE
Runtime.ImportModuleError: Unable to import module 'sample': No module named 'orjson'

### ISSUE THREAD

**Issue by bill2hu** [ijl/orjson#102]
### What did you do?

pip install orjson -t .

### What did you expect to happen?
I am trying to create an AWS lambda function package with python source code, some third party libraries. Along with this library packaged with python source code. Something like this
ll  requests
total 856
-rw-r--r--  1 user1  ANT\Domain Users   3927 Jun  5 20:33 __init__.py
-rw-r--r--  1 user1  ANT\Domain Users   4167 Jun  5 20:33 __init__.pyc
-rw-r--r--  1 user1  ANT\Domain Users    441 Jun  5 20:33 __version__.py
-rw-r--r--  1 user1  ANT\Domain Users    632 Jun  5 20:33 __version__.pyc
-rw-r--r--  1 user1  ANT\Domain Users   1096 Jun  5 20:33 _internal_utils.py
-rw-r--r--  1 user1  ANT\Domain Users   1655 Jun  5 20:33 _internal_utils.pyc
-rw-r--r--  1 user1  ANT\Domain Users  21344 Jun  5 20:33 adapters.py
-rw-r--r--  1 user1  ANT\Domain Users  20180 Jun  5 20:33 adapters.pyc
-rw-r--r--  1 user1  ANT\Domain Users   6496 Jun  5 20:33 api.py
-rw-r--r--  1 user1  ANT\Domain Users   7679 Jun  5 20:33 api.pyc
-rw-r--r--  1 user1  ANT\Domain Users  10207 Jun  5 20:33 auth.py
-rw-r--r--  1 user1  ANT\Domain Users  11539 Jun  5 20:33 auth.pyc
-rw-r--r--  1 user1  ANT\Domain Users    453 Jun  5 20:33 certs.py
-rw-r--r--  1 user1  ANT\Domain Users    646 Jun  5 20:33 certs.pyc
-rw-r--r--  1 user1  ANT\Domain Users   1782 Jun  5 20:33 compat.py
-rw-r--r--  1 user1  ANT\Domain Users   2039 Jun  5 20:33 compat.pyc
-rw-r--r--  1 user1  ANT\Domain Users  18430 Jun  5 20:33 cookies.py
-rw-r--r--  1 user1  ANT\Domain Users  24857 Jun  5 20:33 cookies.pyc
-rw-r--r--  1 user1  ANT\Domain Users   3185 Jun  5 20:33 exceptions.py
-rw-r--r--  1 user1  ANT\Domain Users   8158 Jun  5 20:33 exceptions.pyc
-rw-r--r--  1 user1  ANT\Domain Users   3515 Jun  5 20:33 help.py
-rw-r--r--  1 user1  ANT\Domain Users   3474 Jun  5 20:33 help.pyc
-rw-r--r--  1 user1  ANT\Domain Users    757 Jun  5 20:33 hooks.py
-rw-r--r--  1 user1  ANT\Domain Users   1370 Jun  5 20:33 hooks.pyc
-rw-r--r--  1 user1  ANT\Domain Users  34213 Jun  5 20:33 models.py
-rw-r--r--  1 user1  ANT\Domain Users  31426 Jun  5 20:33 models.pyc
-rw-r--r--  1 user1  ANT\Domain Users    542 Jun  5 20:33 packages.py
-rw-r--r--  1 user1  ANT\Domain Users    511 Jun  5 20:33 packages.pyc
-rw-r--r--  1 user1  ANT\Domain Users  29265 Jun  5 20:33 sessions.py
-rw-r--r--  1 user1  ANT\Domain Users  24142 Jun  5 20:33 sessions.pyc
-rw-r--r--  1 user1  ANT\Domain Users   4188 Jun  5 20:33 status_codes.py
-rw-r--r--  1 user1  ANT\Domain Users   6301 Jun  5 20:33 status_codes.pyc
-rw-r--r--  1 user1  ANT\Domain Users   3005 Jun  5 20:33 structures.py
-rw-r--r--  1 user1  ANT\Domain Users   6186 Jun  5 20:33 structures.pyc
-rw-r--r--  1 user1  ANT\Domain Users  30176 Jun  5 20:33 utils.py
-rw-r--r--  1 user1  ANT\Domain Users  29195 Jun  5 20:33 utils.pyc

### What actually happened?
From the download, I only got a orjson.cpython-37m-darwin.so file and orjson-3.1.0.dist-info folder. This shared library can not be used on AWS lambda service. 

```python
Runtime.ImportModuleError: Unable to import module 'sample': No module named 'orjson' 
```

**Comment by ijl** [comment]
orjson works with normal pip, I don't know how AWS Lambda does site-packages/PYTHONPATH, and can't help.
