### ISSUE TITLE
python json encoder logger

### ISSUE THREAD

**Issue by rspadim** [ijl/orjson#106]
Hi folks!

could be possible integrate orjson into  https://github.com/madzak/python-json-logger?

I think it only need a json.JsonEncoder interface (https://docs.python.org/3/library/json.html#json.JSONEncoder)

https://github.com/madzak/python-json-logger/blob/master/src/pythonjsonlogger/jsonlogger.py

same issue of: https://github.com/madzak/python-json-logger/issues/93

**Comment by ijl** [comment]
Please use https://github.com/madzak/python-json-logger/issues/93, no change is in scope here.
