### ISSUE TITLE
Stabilize codebase

### ISSUE THREAD

**Issue by hendrik-teuber-by** [ijl/orjson#108]
With the release of pyo3 0.11.0 It's now possible to use stable Rust.
Are there any plans to stabilize this repository too?
What would be required?

**Comment by ijl** [comment]
Feel free to look into it. There may be details that make it impractical. Nightly-only features such as intrinsics can have two implementations with a feature flag. maturin probably needs support for specifying features.

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/3.6.2
