### ISSUE TITLE
Support numpy objects

### ISSUE THREAD

**Issue by aviramha** [ijl/orjson#109]
Right now orjson supports numpy arrays, but not plain numpy objects, which is weird.
I suggest adding that the numpy serialize option will support plain numpy objects (numpy.int, etc).

**Comment by ijl** [comment]
The check currently uses the identity of the `numpy.ndarray` type. If you can quickly check others, that'd be fine, too. It can't impact the fallthrough to `default` too much.

**Comment by aviramha** [comment]
I'll submit a PR (or one of my colleagues) soon. Thanks!

**Comment by aviramha** [comment]
Closed with #113

**Comment by ringsaturn** [comment]
object in numpy array seems not supported, on version `3.3.0`

```py
>>> import numpy as np
>>> import orjson
>>> 
>>> data = np.array([{"1": 2}])
>>> orjson.dumps(data, option=orjson.OPT_SERIALIZE_NUMPY)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Type is not JSON serializable: numpy.ndarray
```

**Comment by aviramha** [comment]
@ringsaturn Was it supported before?

**Comment by ringsaturn** [comment]
> @ringsaturn It seems it wasn't supported before so fortunately it's not a regression.
> I think this should be in a new ticket, also I'm not sure how would one implement it.. maybe call the original serialize function when it's an object?

I have the same problem too. It's from a complex object in our production environment so it's not a general problem for orjson.

**Comment by ijl** [comment]
Additional arbitrary types can be different issues.
