### ISSUE TITLE
Deserialize UUID from str

### ISSUE THREAD

**Issue by thinkwelltwd** [ijl/orjson#11]
Hello! orjson is an interesting library! Congratulations on the speed. I would switch to it, but for UUID support. Is there any plan for supporting UUIDs like rapidjson, etc?

**Comment by ijl** [comment]
It's possible. Do you not care to use `default` to serialize UUID?

**Comment by ijl** [comment]
Ok, hm.

**Comment by ijl** [comment]
I'm not interested in doing this anytime soon.
