### ISSUE TITLE
TypeError: dumps() got an unexpected keyword argument

### ISSUE THREAD

**Issue by marc1n** [ijl/orjson#111]
Since version 3.1.0 empty kwargs dict cause an exception in `dumps`:

```python
>>> import orjson
>>> orjson.dumps(None)
b'null'
>>> orjson.dumps(None, **{})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: dumps() got an unexpected keyword argument
```

**Comment by ijl** [comment]
Ok fixed 3.2.1.

**Comment by Leectan** [comment]
@marc1n I wonder if you have found the solution for this.

**Comment by marc1n** [comment]
@Leectan I have found a workaround for this:
```python
options = ...
if options:
  orjson.dumps(obj, **options)
else:
  orjson.dumps(obj)
```

**Comment by marc1n** [comment]
@Leectan See https://github.com/ijl/orjson#migrating: "indent is replaced by option=orjson.OPT_INDENT_2 and other levels of indentation are not supported."
