### ISSUE TITLE
float and UUID subclasses are not serialised

### ISSUE THREAD

**Issue by pxeger** [ijl/orjson#114]
Subclasses of the built-in `float` and standard library `uuid.UUID` are rejected as unserialisable.

```pycon
>>> from uuid import UUID, uuid4
>>> import orjson
>>> class FooUUID(UUID): pass
>>> class FooFloat(float): pass
>>> orjson.dumps(FooFloat(24))
Traceback (most reecent call last):
  File <stdin>, line 1, in <module>
TypeError: Type is not JSON serializable: FooFloat
>>> orjson.dumps(FooUUID(bytes=uuid4().bytes))
Traceback (most reecent call last):
  File <stdin>, line 1, in <module>
TypeError: Type is not JSON serializable: FooUUID
```

This might be intentional, but the wording in the README is not entirely clear:

> serializes subclasses of `str`, `int`, `list`, and `dict` natively, requiring `default` to specify how to serialize others

It doesn't mention subclasses of any of the other types that `orjson` can serialise. I can't really think of any use cases of a subclass of `float` but it's something I noticed while testing my original issue which was about UUID subclasses, and it seems a little random to support `int`, `list`, etc. but not `float`. Is there a reason for this?

The main reason I'm using `orjson` is for its great ability to serialise common "special" objects like UUIDs, and having to switch to the slower intermediate standard-library UUID object isn't great. See https://github.com/MagicStack/asyncpg/issues/512 for a real-world problem caused by this behaviour.

**Comment by ijl** [comment]
float can't be handled efficiently because there's no `Py_TPFLAGS_FLOAT_SUBCLASS` bitflag as there is with others. I don't know why. You could raise it with CPython and I would support it eventually.

UUID subclasses won't be serialized because it's not a builtin type so there's no efficient way to check for subclasses.

**Comment by acnebs** [comment]
For UUID subclasses, is there a less efficient way that could be implemented as only enabled as an option?

**Comment by Kludex** [comment]
Is the following a good workaround for this limitation or is it bad?

```
def default(obj: Any) -> Any:
    type_obj = type(obj)
    if type_obj != float and issubclass(type_obj, float):
        return float(obj)
    raise TypeError

return orjson.dumps(
    content, option=orjson.OPT_NON_STR_KEYS | orjson.OPT_SERIALIZE_NUMPY, default=default
)
```
