### ISSUE TITLE
128-bit integers

### ISSUE THREAD

**Issue by ahopkins** [ijl/orjson#116]
Is there any intent to support serialization of large integers beyond 64 bits?

```python
>>> import orjson, json
>>> json.dumps({"q": 111111111111111111111})
'{"q": 111111111111111111111}'
>>> orjson.dumps({"q": 111111111111111111111})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Integer exceeds 64-bit range
```

**Comment by ijl** [comment]
I don't have any plans. If someone wants to implement this, it needs to roundtrip (serialize and deserialize consistently) and care needs to be taken deserializing integers greater than the 64-bit range written using exponential notation that would become floats right now. What is correct and how do other libraries handle that? Will it be a change in behavior?

**Comment by ddelange** [comment]
I guess blocked by https://github.com/serde-rs/json/issues/846 ?

**Comment by Berserker66** [comment]
Since google brought me here looking for a solution. I need unbounded integers, but 256bit or 512bit would likely suffice. 64bit certainly does not.
I was able to encode an int of any size by abusing Fragment. But when decoding it always becomes a float.

```
import orjson
import unittest


class TestSerialize(unittest.TestCase):
    def test_unbounded_int(self) -> None:
        big_number = 2**200
        round_tripped_big_number = orjson.loads(orjson.dumps(orjson.Fragment(str(big_number).encode())))
        self.assertEqual(big_number, round_tripped_big_number)
        self.assertEqual(type(big_number), type(round_tripped_big_number))
```

**Comment by ddelange** [comment]
fwiw, python integers, and python's json module, support arbitrary side integers:
```pycon
>>> json.dumps(2 ** 512 - 1)
'13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095'
>>> json.dumps(2 ** 513 - 1)
'26815615859885194199148049996411692254958731641184786755447122887443528060147093953603748596333806855380063716372972101707507765623893139892867298012168191'
```

also, it looks like (https://github.com/serde-rs/json/issues/846) orjson could use the `arbitrary_precision` flag?

@ijl could it make sense to re-open this issue?
