### ISSUE TITLE
Support more Numpy data types

### ISSUE THREAD

**Issue by karlhayek** [ijl/orjson#122]
Is there any intent to support more native [Numpy data types](https://numpy.org/devdocs/user/basics.types.html) (e.g. numpy.int16, numpy.uint8, etc.)? 

```python
>>> import orjson, numpy as np
>>> orjson.dumps(np.array([1, 2, 3], dtype=np.int32), option=orjson.OPT_SERIALIZE_NUMPY)
b'[1,2,3]'
>>> orjson.dumps(np.array([1, 2, 3], dtype=np.int8), option=orjson.OPT_SERIALIZE_NUMPY)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Type is not JSON serializable: numpy.ndarray

```

**Comment by ijl** [comment]
Feel free to add any. For each type there is documentation, the array path, and the scalar path.

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/3.4.0
