### ISSUE TITLE
Documentation correction

### ISSUE THREAD

**Issue by beached** [ijl/orjson#124]
Slight correction to https://github.com/ijl/orjson#int The first sentence "JSON only requires that implementations accept integers with 53-bit precision" is not correct.  JSON places no restrictions on the scale of number types but allows for reasonable limits.  The 53 bit limit is a result of JavaScript using double for the representation of numbers.

**Comment by ijl** [comment]
Ok, thanks, sort of fixed now.

**Comment by beached** [comment]
One option when encoding larger than 53 bit numbers is to make them strings.  It's not for all cases, but it's pretty common too I think.  Then a BigInt in javascript can use it, many browsers have it as part of the lang now https://caniuse.com/bigint

**Comment by ijl** [comment]
I suppose someone could propose a solution for bigints in #116.
