### ISSUE TITLE
More easily support other Serializers

### ISSUE THREAD

**Issue by vdwees** [ijl/orjson#126]
This library is excellent! The performance is excellent, but what I really appreciate is the correct handling of NaN and datetimes. 

Is there any interest to add support for injecting the Serializer/Deserializer?  In particular, I have msgpack in mind, perhaps via [rmp-serde](https://docs.rs/rmp-serde). With a small refactor, this library could be published and used in a more general-purpose manner.

**Comment by ijl** [comment]
It's an interesting idea but I think this library's implementation is very specific to JSON. I suggest just copying parts you find useful.
