### ISSUE TITLE
Deserialization Performance

### ISSUE THREAD

**Issue by frnkvieira** [ijl/orjson#13]
Any chance to improve deserialization performance and beat **ujson** on cases like bellow ?

```py
import ujson
import orjson
import time

# A naive benchmark but it shows what I mean :P
data = '{"a": 1, "b": 2, "c": 3, "d": 4, "e": 5, "f": "useless-bench"}'
u = ujson.loads
o = orjson.loads

t2 = time.time()
for _ in range(0, 1_000_000):
    o(data)
print(time.time() - t2)
# 0.634258508682251

t1 = time.time()
for _ in range(0, 1_000_000):
    u(data)
print(time.time() - t1)
# 0.5261068344116211
```
I mean, this library is slightly slower in deserialization thanks to a "correct" approach or it's just not optimized enough for this use case ?

Personal Note: thanks for the published wheels :)

**Comment by ijl** [comment]
ultrajson works with UTF32, which Python uses internally, while orjson works with UTF8. That's the most obvious difference between the two implementations. It's not possible to change that at a reasonable cost.
