### ISSUE TITLE
__module__ returns a non-string value

### ISSUE THREAD

**Issue by ChenghaoMou** [ijl/orjson#131]
The official definition of `__module__` attribute is  

> The name of the module the function was defined in, or None if unavailable.
> https://docs.python.org/3/reference/datamodel.html

But `orjson` returns a module object:

```
>>> import orjson
>>> orjson.dumps.__module__
<module 'orjson' from '/opt/conda/envs/sdk/lib/python3.7/site-packages/orjson.cpython-37m-x86_64-linux-gnu.so'>
>>> import json
>>> json.dumps.__module__
'json'
```

which makes it incompatible with some other libraries like`dask` that try to read the module name.

**Comment by ijl** [comment]
Ok, thanks, fixed.

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/3.4.1
