### ISSUE TITLE
Unable to build dependency packed_simd on windows

### ISSUE THREAD

**Issue by Congee** [ijl/orjson#132]
I am using `rustc 1.49.0-nightly (beb5ae474 2020-10-04)` and python 3.9 on windows 10.

It's an upstream issue that has already been fixed. see https://github.com/rust-lang/packed_simd/issues/288#event-3799467220

Any workaround?

**Comment by ijl** [comment]
> Problems with the Rust nightly channel may require pinning a version. nightly-2020-09-14 is known to be ok.
