### ISSUE TITLE
Missing wheel for Python 3.9 (Windows, macOS)

### ISSUE THREAD

**Issue by mozesa** [ijl/orjson#134]
**Hello!**

I cannot install `orjson` with command `pip install orjson`.

The traceback is the following.

OS: Windows 10 (64bit)
Python: 3.9 (64bit)

I have tried both installing git master, and the latest orjson, no success.

Thanks for your help in advance.

```
Collecting orjson
  Using cached orjson-3.4.0.tar.gz (655 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'

DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated. pip 20.3 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\mozesa\PycharmProjects\acps-asm-core\.venv\Scripts\python.exe' 'C:\Users\mozesa\PycharmProjects\acps-asm-core\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\mozesa\AppData\Local\Temp\tmpw9exnck8'
         cwd: C:\Users\mozesa\AppData\Local\Temp\pycharm-packaging\orjson
    Complete output (6 lines):
    Checking for Rust toolchain....
    
    Cargo, the Rust package manager, is not installed or is not on PATH.
    This package requires Rust and Cargo to compile extensions. Install it through
    the system's package manager or via https://rustup.rs/
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\mozesa\PycharmProjects\acps-asm-core\.venv\Scripts\python.exe' 'C:\Users\mozesa\PycharmProjects\acps-asm-core\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\mozesa\AppData\Local\Temp\tmpw9exnck8' Check the logs for full command output.
```

**Comment by mozesa** [comment]
It works with `pip3.8 install orjson` but not with ˙pip3.9`.

**Comment by iwoloschin** [comment]
It appears that there is also a missing wheel for python3.9 on macOS, the missing wheel should be `orjson-3.4.0-cp39-cp39-macosx_10_7_x86_64.whl`. A similar wheel exists for python3.8 on macOS and since python3.9 was just released two days ago I assume we just need to get some new wheels generated?

**Comment by iwoloschin** [comment]
In the meantime, `orjson` installs fine on macOS as long as you've set `rustup default nightly-2020-09-14` and ensure you have `maturin` installed (either globally or in the virtual environment). I assume the same is true of Windows?

**Comment by ijl** [comment]
"next week" per https://github.com/actions/virtual-environments/issues/1740

**Comment by tedtieken** [comment]
@iwoloschin can confirm that setting rust to nightly-2020-09-14 fixed the issue blocking installation on windows (64 bit, cpython 3.9)

**Comment by mozesa** [comment]
[Windows environments](https://github.com/actions/virtual-environments#available-environments) have rolled out. 🎉

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/3.4.2
