### ISSUE TITLE
Fail to install 3.4.0 with pip3

### ISSUE THREAD

**Issue by shannon197751** [ijl/orjson#136]
I could not install orjson 3.4.0 with pip3 on Linux. 

[docker]   Downloading https://files.pythonhosted.org/packages/ca/ab/cece004aaae000741d059dcb9b1f6f62a6a5ecb2e11b3ecca09e6180c327/orjson-3.4.0.tar.gz (655kB)
[docker]     Complete output from command python setup.py egg_info:
[docker]     Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib64/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-di2xujrs/orjson/setup.py'

3.3.1 works for me

**Comment by elrik75** [comment]
Same error for me since version 3.4.0. It work perfectly in 3.3.1
Python 3.7.3 on Debian Buster + venv

```
  Downloading https://files.pythonhosted.org/packages/ca/ab/cece004aaae000741d059dcb9b1f6f62a6a5ecb2e11b3ecca09e6180c327/orjson-3.4.0.tar.gz (655kB)
    100% |████████████████████████████████| 665kB 2.2MB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-h42lglj_/orjson/setup.py'
```

**Comment by lunswor** [comment]
Getting the same error as above

**Comment by amagee** [comment]
Same issue here. For what it's worth, I was able to solve it by upgrading from Python 3.6.12 to 3.8.6.

**Comment by Michaelliv** [comment]
`python -m pip install --upgrade pip` seems to solve it

**Comment by ijl** [comment]
Yes, you need to upgrade pip: https://github.com/ijl/orjson#why-cant-i-install-it-from-pypi

**Comment by elrik75** [comment]
I confirme that upgrading pip has solved the issue.
