### ISSUE TITLE
Package for Debian

### ISSUE THREAD

**Issue by aos** [ijl/orjson#138]
Hey there! Thanks for this library, it is very useful (and fast!). I noticed that there is no Debian package available for it. I also don't see it on the [Debian package request tracker](https://wnpp.debian.net/?type%5B%5D=ITA&type%5B%5D=ITP&type%5B%5D=O&type%5B%5D=RFA&type%5B%5D=RFH&type%5B%5D=RFP&project=orjson&description=&owner%5B%5D=yes&owner%5B%5D=no&col%5B%5D=dust&col%5B%5D=type&col%5B%5D=description&col%5B%5D=installs&sort=project). Would this be something you're interested in?

I have experience packaging python into `apt` packages. I'm happy to work on this if it is meaningful.

**Comment by ijl** [comment]
If you'd like it in Debian for your needs, feel free to try and I can accept patches if needed. I think Debian is likely to have issues with a few things. First, I think Debian has a self-hosting requirement, so [maturin](https://github.com/PyO3/maturin) also needs to be packaged. That compiles on stable Rust and if something in Rust is fine should not be difficult. But then this project uses Rust nightly, and that nightly version may be some arbitrary date in conflict with a system-wide toolchain.

**Comment by aos** [comment]
Ah I didn't know this project follows Rust nightly -- that might be difficult to package! Any plans to eventually switch to stable? If that is the case, I would rather hold off until then. I can of course package the PyPI version into Debian but that feels a little bit arbitrary :-)

Thanks!

**Comment by ijl** [comment]
Ok.

**Comment by eddybl** [comment]
@aos did you ever revisit this topic? I would love to have a debian package of this :o
