### ISSUE TITLE
Regression in parsing JSON between 3.4.1 and 3.4.2

### ISSUE THREAD

**Issue by marco-c** [ijl/orjson#139]
```Python
import orjson

s = '{"cf_status_firefox67": "---", "cf_status_firefox57": "verified"}'

orjson.loads(s)["cf_status_firefox57"]
```

This works in 3.4.1, throws `KeyError: 'cf_status_firefox57'` in 3.4.2.

**Comment by marco-c** [comment]
`orjson.loads(s)` is `{'cf_status_firefox67': 'verified'}`, which is clearly wrong.

**Comment by ijl** [comment]
Oh, thanks for the report. Fixed in https://github.com/ijl/orjson/releases/tag/3.4.3 with your test case added.
