### ISSUE TITLE
datetime support break default function

### ISSUE THREAD

**Issue by phyng** [ijl/orjson#14]
Before version 2.0.2 we use `DjangoJSONEncoder.default` to handle datatime, but it doesn't works now, and  the orjson datetime is not compatible with the logic below:

https://github.com/django/django/blob/master/django/core/serializers/json.py#L81

```python
def default(self, o):
    # See "Date Time String Format" in the ECMA-262 specification.
    if isinstance(o, datetime.datetime):
        r = o.isoformat()
        if o.microsecond:
            r = r[:23] + r[26:]
        if r.endswith('+00:00'):
            r = r[:-6] + 'Z'
        return r
    elif isinstance(o, datetime.date):
        return o.isoformat()
    elif isinstance(o, datetime.time):
        if is_aware(o):
            raise ValueError("JSON can't represent timezone-aware times.")
        r = o.isoformat()
        if o.microsecond:
            r = r[:12]
        return r
    elif isinstance(o, datetime.timedelta):
        return duration_iso_string(o)
    elif isinstance(o, (decimal.Decimal, uuid.UUID, Promise)):
        return str(o)
    else:
        return super().default(o)
```

Is there a way to make default works with datetime object?

**Comment by ijl** [comment]
It serializes supported objects before `default` is called. What are the differences you would like on datetime objects? I see `Z` instead of `+00:00` and the ability to not serialize microseconds. The latter is possible. I don't immediately see a reason to prefer `Z`.

**Comment by phyng** [comment]
@ijl 

The key differences is: `DjangoJSONEncoder` serializes `datetime.datetime.now()` to `2019-03-27T09:37:02.516`, but `orjson 2.0.3` is `...+00:00`, I must guarantee compatibility for our API.

In JavaScript:

```javascript
new Date(`2019-03-27T09:37:02.516`)
// Wed Mar 27 2019 09:37:02 GMT+0800 (CST)
new Date(`2019-03-27T09:37:02.516+00:00`)
// Wed Mar 27 2019 17:37:02 GMT+0800 (CST)
```

Since handle `datatime` object in `default` function is a common operation and different developers have their own format, mayby we can add a option to serializes `datetime` with `default` ?

```python
In [1]: from tools.common.json_tool import fast_dumps_str

In [2]: import datetime

In [3]: now = datetime.datetime.now()

In [4]: now
Out[4]: datetime.datetime(2019, 3, 27, 9, 37, 2, 516478)

In [5]: now.microsecond
Out[5]: 516478

In [6]: now.tzinfo

In [7]: o = now

In [8]: r = o.isoformat()

In [9]: r = r[:23] + r[26:]

In [10]: r
Out[10]: '2019-03-27T09:37:02.516'

In [11]: fast_dumps_str({"date": now})
Out[11]: '{"date":"2019-03-27T09:37:02.516"}'

```

**Comment by ijl** [comment]
I'll look into overriding orjson serializing datetime objects. It also makes sense for another use case to allow serializing `datetime.datetime` objects without a `tzinfo`. I could make orjson output three digits of microseconds and match Django, but I don't see a reason to prefer that over Python's full precision, so it looks like you do need to avoid its handling.

**Comment by phyng** [comment]
@ijl Thanks!

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/2.0.4 is a partial solution. You do want the ability to totally disable it due to microsecond precision, right, @phyng?

**Comment by phyng** [comment]
I think it is ok now, three digits or six digits is ok. Thank you very much!

```python            
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import orjson
>>> import datetime
>>> orjson.dumps(datetime.datetime.now())
b'"2019-04-03T08:00:28.473661"'
```
