### ISSUE TITLE
Cannot pip install orjson (python 3.6).

### ISSUE THREAD

**Issue by loomcode** [ijl/orjson#140]
```
sudo pip3 install --upgrade orjson:

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-3dwbn4b3/orjson/setup.py'
```
Not sure why it can't find setup when it was just downloaded.  I've verified that it exists in the source.

**Comment by neepoo** [comment]
I've got the same problem.

**Comment by neepoo** [comment]
> I've got the same problem.

Version 3.4.0 cannot be installed, version 3.3.0 can be installed.

**Comment by alexprengere** [comment]
You probably have an old pip. Try upgrading pip first:
```
python -m pip install --upgrade pip
```
I had the same issue with pip version 18, latest version fixes the issue.

**Comment by ijl** [comment]
I have maybe made this obvious in https://github.com/ijl/orjson#install now.

**Comment by loomcode** [comment]
> You probably have an old pip. Try upgrading pip first:
> 
> ```
> python -m pip install --upgrade pip
> ```
This worked for me.

**Comment by ludaavics** [comment]
@ijl 

I can install manually via pip, but [project requirements](https://github.com/ijl/orjson/blob/master/Cargo.toml#L31) (and readme) state python >=3.7 which prevent adding orjson in dependency management tools like [Poetry](https://python-poetry.org/).
Any chance to lower those to 3.6?

Thanks!

**Comment by ludaavics** [comment]
nvm i see you just dropped 3.6 support, i'll just pin to previous version.

**Comment by drewm1980** [comment]
Python 3.6 support was removed, and coincidentally, support for correct round-tripping of float -> json -> float were added in the same release 3.6.2.

Can anyone clarify if there is a known problem with orjson 3.6.2 on python3.6, or is it just a matter of building it myself without support?

**Comment by drewm1980** [comment]
Put another way, was there a non-trivial technical reason for dropping python 3.6 when you did?

**Comment by drewm1980** [comment]
Found it:
commit a116ddf1d5745c7d8a5af417d76de9b0c6ee2bdf
Author: ijl <ijl@mailbox.org>
Date:   Sun Aug 15 17:33:55 2021 +0000

    pyo3 ^0.14.2
    
    python3.6 is dropped because it's nearly end of life and there
    is now assertion error in pyo3::gil::prepare_freethreaded_python
    in CI when running integration/thread.

**Comment by drewm1980** [comment]
The version with the float round-tripping that I want was introduced in:
2719fc724eef85b2fadcf86159d49ec5fe5b096f

**Comment by drewm1980** [comment]
So unfortunately for me, there was no commit for python 3.6 with correct round-tripping of floating point numbers.

**Comment by GabrielAbdul** [comment]
> You probably have an old pip. Try upgrading pip first:
> 
> ```
> python -m pip install --upgrade pip
> ```
> 
> I had the same issue with pip version 18, latest version fixes the issue.

This worked for me
