### ISSUE TITLE
pip install --target ./package orjson>=3.4.3 

### ISSUE THREAD

**Issue by sbwhitney** [ijl/orjson#141]
I would like to package up the deps for an AWS Lambda function by installing to a target directory. I can pip install orjson normally with no issue locally, but when I set the target all I get in the target directory is this file orjson.cpython-38-darwin.so and a dist-info folder. I then try to deploy the package folder with the lambda and the deploy fails because it cannot import orjson.

**Comment by artc95** [comment]
hi @sbwhitney ! what was the solution?

**Comment by sbwhitney** [comment]
https://github.com/nazrulworld/fhir.resources/blob/92f71a12ca19559491074845502b02f2504d5ae0/fhir/resources/core/fhirabstractmodel.py

The library author made orjson not mandatory by substituting simplejson if ImportError

**Comment by artc95** [comment]
(very delayed) thanks @sbwhitney !!!
anyway I would recommend using Docker images with Lambda (instead of package folder and .zip),
official guide https://docs.aws.amazon.com/lambda/latest/dg/python-image.html#python-image-instructions
or let me know if I can help :)
