### ISSUE TITLE
Question on `os.sched_setaffinity()`

### ISSUE THREAD

**Issue by eblume** [ijl/orjson#142]
Hello, I have a question about the 7 calls to `os.sched_setaffinity(os.getpid(), {0, 1})` in this package's python code. I've searched for those calls here: https://github.com/ijl/orjson/search?q=sched_setaffinity

My understanding of `os.sched_setaffinity(os.getpid(), {0, 1})`, placed in module-level code, is that any process that imports the containing module will have its processor affinity set to only allow it to be scheduled on cores 0 and 1.

Would you please tell me why orjson must do this? Is it something to do with the rust integration? Should code that imports orjson be aware that this affinity restriction is being set? What happens to multi-processing code, or code running in a gunicorn AsyncWorker, for instance?

Thanks for any help you can give on this! If you prefer questions be sent to a different location, please let me know and I'll happily redirect.

**Comment by ijl** [comment]
This is done to reduce noise in benchmarks. These aren't included in the shipped artifact. It has the effect that you think, but each of those statements is in a module that is either standalone or is called from another benchmarking script, i.e., it's not part of the orjson module. If you want to follow what's installed, look at `site-packages` or an unzipped binary wheel. It's only the compiled shared object and a `dist-info` (package metadata) folder.

**Comment by eblume** [comment]
I see, thank you!
