### ISSUE TITLE
possible to escape already jsonified string ?

### ISSUE THREAD

**Issue by sdementen** [ijl/orjson#146]
I am working with pandas objects that have a very fast to_json() method to serialise pandas.Series.
I need to serialize a dict with some elements which are pandas objects, e.g.:
`{ "data": pandas.Series(...) }`
I would like to be able to transform the dict as
`{ "data": SerializedJSON("[1,3,4, ...]") }`
with
```
class SerializedJSON(str):
    """An object of type SerializedJSON is a string that will be injected as such in the finale JSON string"""
    pass
```
so that orjson would not escape again this string.

Does this make sense ? Would it be useful to add this SerializedJSON ?

**Comment by ijl** [comment]
It's too complex for me to want to accept or maintain. I suggest using python-rapidjson's RawJSON. If you have another way of supporting pandas, sure.

**Comment by sdementen** [comment]
Thank you for your suggestion, it is exactly what I was looking for!

**Comment by bryceschober** [comment]
To follow up on this... the solution is to use python-rapidjson instead of orjson? Or to use its RawJSON object to wrap `pandas.to_json()` in a orjson `default` handler?
