### ISSUE TITLE
Expose a method to check if a given ndarray can be serialized or not

### ISSUE THREAD

**Issue by orf** [ijl/orjson#148]
Hello 👋,
Thanks for this awesome project! I'm using it inside an internal library that may be passed an incompatible numpy array from the user of the library. Ideally I'd like to detect if the `ndarray` _can_ be serialized using the orjson fast-path before I call `orjson.dumps()`.

Would you accept a PR that exposed a function to Python, like so:

```rust
pub fn can_serialize_ndarray(ob_type: *mut PyTypeObject) -> bool {
    is_numpy_scalar(ob_type) || is_numpy_array(ob_type)
} 
``` 

Consumers of `orjson` could then be smarter about passing in ndarrays to dumps:

```python
contents = [incompatible_ndarray, compatible_ndarray]
safe_contents = [
    ndarray.tolist()   # Slow :(
    if orjson.can_serialize_ndarray(ndarray)
    else ndarray       # Fast :)
    for ndarray in contents
]
orjson.dumps(contents)
```

**Comment by ijl** [comment]
This is a use case for default. It will be faster than going through your data before calling.

```python
contents = [incompatible_ndarray, compatible_ndarray]
def default(obj):
    if isinstance(obj, numpy.ndarray):
        return obj.tolist()
    raise TypeError

orjson.dumps(contents, default=default)
```

 If you would like to add support for unsupported array types, that'd also help.

**Comment by orf** [comment]
Duh! Of course, my bad. Thanks for the reply!
