### ISSUE TITLE
Cannot serialize dicts with datetime keys

### ISSUE THREAD

**Issue by cstigen** [ijl/orjson#156]
Hi,

I'm using orjson 3.4.7. While the below works as expected (runs `isoformat` or something equivalent on the datetime object)

```
>>> orjson.dumps({"test": datetime.datetime.now()})
b'{"test":"2021-01-21T19:01:52.722286"}'
```

... swapping keys and values does not:

```
>>> orjson.dumps({datetime.datetime.now(): "test"})                                                                                                           
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Dict key must be str

```
I may be naive, but I would expect this to work. Am I missing something? The only possible problem I can see (if you had allowed it) is in case two different datetime objects end up colliding after doing an isoformat-like translation.

Should I just proceed doing the translation myself, or do you guys think this can be considered a missing feature or some kind of bug?

**EDIT:** I have to say I see similar behavior in other libraries, for example `flask.jsonify` and pydantic doesn't like datetime keys either (although pydantic will happily accept them until you try serializing them to json).

**Comment by ijl** [comment]
Yes, you need to opt-in to this with https://github.com/ijl/orjson#opt_non_str_keys due to collisons as you said.
