### ISSUE TITLE
Import Error in Docker CentOS7.7.1908 Python3.7.9 （AArch64）

### ISSUE THREAD

**Issue by Zacama** [ijl/orjson#160]
![image](https://user-images.githubusercontent.com/50320281/106848586-2f7d7c00-66ec-11eb-8434-669921ed18bb.png)
![image](https://user-images.githubusercontent.com/50320281/106848621-42904c00-66ec-11eb-8ed3-27d343819ab7.png)
![image](https://user-images.githubusercontent.com/50320281/106849239-525c6000-66ed-11eb-864c-e7ba9516756a.png)

**Comment by Zacama** [comment]
![image](https://user-images.githubusercontent.com/50320281/106848861-b894b300-66ec-11eb-8a34-173c2fe3efaa.png)
Hello ，I noticed that OrJSON does not depend on GLIBC2.18 since 2.5.1. I wonder why this error occurs

**Comment by ijl** [comment]
I've moved the aarch64 builders to use manylinux2014 images. I think that resolves it. Fixed in https://github.com/ijl/orjson/releases/tag/3.4.8

**Comment by Zacama** [comment]
Thank you verrrrry much!!!! It takes effect!
