### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by Gelbpunkt** [ijl/orjson#161]
Hi there, I'm trying to decode Rust JSON strings and byte slices to PyObjects and encode python objects to Rust strings/byte slices.
For that, writing my own would be a lot of work that orjson already did and copying over files is not what I really want to do.

Would it be possible to publish the internal serialize and deserialize functions to crates.io for use in other pyo3-based modules?

**Comment by ijl** [comment]
The only public API is the C functions and objects exported to the orjson Python module. So I don't see a benefit to having it as a Rust dependency. Vendoring it just to ensure it's installed would be unnecessary and would break with usual packaging and distribution. I suggest having your project have a dependency in `setup.py` or `pyproject.toml` on orjson, then import it like:

```rust
let module = PyImport_ImportModule("orjson\0".as_ptr() as *const c_char);
let module_dict = PyObject_GenericGetDict(module, std::ptr::null_mut());
let loads = PyMapping_GetItemString(module_dict, "loads\0".as_ptr() ....
```

**Comment by ijl** [comment]
Feel free to reopen. Also the above could be finished and become a recipe in the README.

**Comment by JackThomson2** [comment]
Hi @ijl awesome library, I see you've closed this issue. I've been doing a bit of work on the robyn python server. As the backend is written in rust it'd be awesome if a user could return a python type and we can consume your library so send json as a response. Any thoughts on this? 

I understand your solution above, but I think for a webserver where speed is important I wonder if you could expose your serialisation implementations?

Jack

**Comment by ijl** [comment]
I think it's the same story: the public API is the in-Python API. You would get the pointer to `orjson.loads` and call it appropriately. I think writing a recipe would be good. If there's some substantial improvement to a Rust-specific API you see we could talk about that but it's not obvious to me and a lot of work.
