### ISSUE TITLE
Support serializing generators?

### ISSUE THREAD

**Issue by vdboor** [ijl/orjson#162]
Parts of my code have a generator. I'd love to see orjson consume these directly to reduce memory usage.

Currently I'm serializing these using the `default` setting:

```
def _default(data):
    if inspect.isgenerator(data) or isinstance(data, itertools.chain):
        return list(data)
    raise TypeError

orjson.dumps(data, _default)
```

However, as this consumes more memory I'd love to see native support instead.

**Comment by ijl** [comment]
Feel free to propose an implementation. I suspect it would need to be behind a flag even on a new major version because a test for `__iter__` will be very broad.

**Comment by deantvv** [comment]
This may need more support on `pyo3` side to implement `genobject.c` [cpython](https://github.com/python/cpython/blob/master/Objects/genobject.c) into `src/ffi/cpython/genobject.rs` like `src/ffi/cpython/listobject.rs` [pyo3](https://github.com/PyO3/pyo3/blob/main/src/ffi/cpython/listobject.rs) does.
