### ISSUE TITLE
Problem with FreeBSD

### ISSUE THREAD

**Issue by zafon18** [ijl/orjson#163]
I am using the FreeBSD project and I am having trouble installing the package. Does the orjson package support FreeBSD?

**Comment by ijl** [comment]
I'll accept a patch fixing an issue on FreeBSD but there's no available CI.

**Comment by zafon18** [comment]
Thanks a lot for your help and quick reply. greetings

**Comment by messense** [comment]
> I'll accept a patch fixing an issue on FreeBSD but there's no available CI.

Actually there is [Cirrus CI](https://cirrus-ci.org/) which supports FreeBSD and is free for OSS projects.

**Comment by rozhuk-im** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=266213
