### ISSUE TITLE
Support python3 stdlib arrays

### ISSUE THREAD

**Issue by etianen** [ijl/orjson#168]
Numpy is a pretty huge dependency, and in some cases it would be nice to benefit from the faster serialization and lower memory footprint of a python stlib array without importing a 3rd party dependency.

https://docs.python.org/3/library/array.html

**Comment by ijl** [comment]
Probably nothing happening here.

**Comment by 2-5** [comment]
@ijl I would also like this, `array.array` is a strict subset of `numpy.ndarray`, so it seems it would be a simple case of copy/pasting the `ndarray` implementation and deleting extra stuff (like timestamp support). Unfortunately I don't know Rust to make a PR.

One use case is serializing millions of numbers returned from a database, using `array` to avoid creating a large intermediate `list` (lots of memory allocations), while also avoiding `numpy` which is a big dependency.

**Comment by sm-Fifteen** [comment]
I'm also going to add my vote on this issue, for the reasons listed by 2-5. I currenly have numpy installed on an API service solely for fast serialization of number lists by orjson. When I last compared (encoding the equivalent of a dozen 96 rows*100 cols dataframe into json row by row), it was 30 times faster to encode the rows as `LineDataclass(foo, bar, data_line=np.array(row_100_floats, dtype=float, order='C'))` than as `LineDataclass(foo, bar, data_line=row_100_floats)`.

That's not only a very significant speed gain, it also means JSON encoding won't keep hold of the GIL for extended durations, which is very important when dealing with multithreaded and async use cases. The only problem is that this requires pulling numpy (which is 150 times bigger than orjson) merely to use ndarray as an intermediate selialization format.
