### ISSUE TITLE
Support python enum in dumps

### ISSUE THREAD

**Issue by renanvieira** [ijl/orjson#17]
I have the following dict to serialize: 
```python
{ 'localDate': '02/02/2002', 'merchant': '1234', 'id': '54243', 'status': <StatusEnum.ok: 'OK'>, 'trace': 243242}
```
StatusEnum: 
```python
class StatusEnum(str, Enum):
     ok = "OK"
     canceled = "C"
     deleted = "DEL"
```

This `dict` works with both `json` and `ujson`, serializing to the string value, but with `orjson` I get the following error:
```
orjson.JSONEncodeError: Type is not JSON serializable: StatusEnum
```

I wish to know enough Rust to contribute with this, but it's possible to ujson receive the enum and get the value to the output json string?

**Comment by ijl** [comment]
You can use `default` to serialize this right now. It's possible to add it if all cases can be handled. Looking quickly at CPython, `json` doesn't serialize `Enum`, it serializes subclasses of int and str, which the example `StatusEnum` and the stdlib `IntEnum` are.

**Comment by renanvieira** [comment]
I have a large application who do not encapsulate the calls to `ujson` making a little complicated to migrate from `ujson` to `orjson`, can we implement this behavior in `orjson` to make migrations like this work smoother?

**Comment by ijl** [comment]
I suggest implementing the missing wrapper.
