### ISSUE TITLE
Feature request for dumps decimal

### ISSUE THREAD

**Issue by linrongbin16** [ijl/orjson#172]
Hi, would orjson support dumps decimal ?

**Comment by ijl** [comment]
Someone could propose an implementation starting from documentation. The Rust implementation likely requires the float case be serialized as bytes after using something like rust-decimal.

**Comment by ijl** [comment]
Someone can open a new issue documenting how they would handle serializing as f64, serializing as str, and the implementation of them, performance, and edge cases.
