### ISSUE TITLE
Publish python3.8 wheels

### ISSUE THREAD

**Issue by ijl** [ijl/orjson#18]
Depends on https://github.com/microsoft/azure-pipelines-image-generation/issues/905.

**Comment by ijl** [comment]
2.0.11 published a `cp38-cp38-manylinux1_x86_64` wheel.

**Comment by ijl** [comment]
https://github.com/microsoft/azure-pipelines-image-generation/issues/1317

**Comment by richardhanson** [comment]
Appreciate you being on top of this issue! Now that Azure Pipelines seem to have support, can you cut macOS and Windows wheels please?

**Comment by ijl** [comment]
Published in 2.1.3.

**Comment by richardhanson** [comment]
Thanks so much. Appreciate the quick turnaround!
