### ISSUE TITLE
Support numpy.datetime64 types

### ISSUE THREAD

**Issue by sd2k** [ijl/orjson#182]
It would be fantastic if there was a way to directly support numpy's datetime64 types. Currently the only real alternative to serialize an array of them is to first convert them to Python datetimes, then use `array.tolist()`, which introduces a lot of overhead.

I've had a look at doing this (just using `chrono` to actually handle the serialization for now), and there are a few difficulties. While it's fairly simple to add a new `ItemType::DATETIME64` variant and a new arm to the match statement in `ItemType::find` (`            (077, 8) => Some(ItemType::DATETIME64),`), numpy actually represents datetime64 objects very differently depending on the date/time unit used when creating them. Specifically, numpy always stores a single i64 per element, but that i64 can mean different things depending on the unit. So `numpy.datetime("2021")` is represented as `51` (51 years since the epoch), `numpy.datetime("2021-01")` as `612`, etc.

Inside Python you can use the `array.dtype.descr` attribute to determine the unit:

```
>>> numpy.datetime64("2021").dtype.descr
[('', '<M8[Y]')]
>>> numpy.datetime64("2021-01").dtype.descr
[('', '<M8[M]')]
>>> numpy.datetime64("2021-01-01").dtype.descr
[('', '<M8[D]')]
>>> numpy.datetime64("2021-01-01T00").dtype.descr
[('', '<M8[h]')]
>>> numpy.datetime64("2021-01-01T00:00").dtype.descr
[('', '<M8[m]')]
>>> numpy.datetime64("2021-01-01T00:00:00").dtype.descr
[('', '<M8[s]')]
```

But according to https://github.com/numpy/numpy/issues/5350, the `descr` of the `__array_struct__` isn't filled in for datetime64 arrays, so it's not trivial to discover the unit from the C side (unless I'm missing something obvious!)

I'd be happy to submit a PR for this if anyone has any ideas on how to access that string :thinking:

**Comment by ijl** [comment]
I agree with including it. It should probably support the same options that apply to Python datetimes. Not sure if that's practical with chrony.

**Comment by sd2k** [comment]
@ijl thanks for merging #183! Would it be possible to get a new release with those changes in?

**Comment by ijl** [comment]
Yes, in https://github.com/ijl/orjson/releases/tag/3.6.0.
