### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by tubbytoons** [ijl/orjson#189]
Cant install with PyPy, upgraded downgraded tried alot lmk if you have the same issue or fix

**Comment by kingofsystem** [comment]
Have same issue when `pip install orjson`, cannot install any version:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/tokenize.py", line 392, in open
    buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-ov0rvt35/orjson/setup.py'
```

**Comment by AdamBrianBright** [comment]
Works fine on Python 3.9.6 and 3.8.8 on MacOS BigSur 11.0.1
| 3.9.6 poetry | 3.8.8 poetry | 3.9.6 pip |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/15821800/127004649-b987234f-40b7-437f-99c3-765da82c0507.png) | ![image](https://user-images.githubusercontent.com/15821800/127005190-56283d21-6452-444f-9c07-64d37327224a.png) | ![image](https://user-images.githubusercontent.com/15821800/127005513-dce583b0-d910-4705-9f21-2a43b999eb67.png) |

**Comment by aviramha** [comment]
orjson doesn't support pypy
![image](https://user-images.githubusercontent.com/41201924/127145010-1d134742-0e48-4432-a777-c6381195bf87.png)

**Comment by the-wondersmith** [comment]
@ijl I'm happy to do the work in Rust to get things working with PyPy if you'll just let me know what exactly the issue is / what needs to be done.

**Comment by ijl** [comment]
It would be very involved, so I can only suggest looking at the source. Probably not practical.
