### ISSUE TITLE
Fails to compile with Rust stable or nightly @ 08/01/2021

### ISSUE THREAD

**Issue by cydergoth** [ijl/orjson#191]
OS: Alpine docker 

```
Collecting orjson==3.5.2
  Downloading orjson-3.5.2.tar.gz (740 kB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpqow28n1a
         cwd: /tmp/pip-install-a43st5i4/orjson_f62ec72f3d1543969a9ea565958d90fa
    Complete output (11 lines):
    💥 maturin failed
      Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
      Caused by: `cargo metadata` exited with an error: error: failed to run `rustc` to learn about target-specific information

    Caused by:
      process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Z mutable-noalias=yes -C target-feature=+sse2,-crt-static --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
      --- stderr
      error: the option `Z` is only accepted on the nightly compiler
    Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-b427vvxj', '--interpreter', '/usr/local/bin/python', '--manylinux=off', '--strip=on']' returned non-zero exit status 1.
    Checking for Rust toolchain....
    Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-b427vvxj --interpreter /usr/local/bin/python --manylinux=off --strip=on`
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/50/3d/31803e13b4ddd271047b6a62366bd4abd2cb08dc55a0b47a8b3b2dc2dbc7/orjson-3.5.2.tar.gz#sha256=f385253a6ddac37ea422ec2c0d35772b4f5bf0dc0803ce44543bf7e530423ef8 (from https://pypi.org/simple/orjson/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpqow28n1a Check the logs for full command output.
```

**Comment by cydergoth** [comment]
Building wheel for orjson (PEP 517): started
  Building wheel for orjson (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpay_ykw32
       cwd: /tmp/pip-install-9p9zfq56/orjson_7d728d95dcd040108ffe70eedd910825
  Complete output (134 lines):
  Running `maturin pep517 build-wheel -i /usr/local/bin/python --manylinux=off --strip=on`
     Compiling cfg-if v1.0.0
     Compiling libc v0.2.93
     Compiling libm v0.1.4
     Compiling ryu v1.0.5
     Compiling packed_simd_2 v0.3.4
     Compiling bitflags v1.2.1
     Compiling cfg-if v0.1.10
     Compiling serde v1.0.125
     Compiling getrandom v0.2.2
     Compiling smallvec v1.6.1
     Compiling lexical-core v0.7.5
     Compiling version_check v0.9.3
     Compiling scopeguard v1.1.0
     Compiling arrayvec v0.5.2
     Compiling encoding_rs v0.8.28
     Compiling static_assertions v1.1.0
     Compiling pyo3 v0.13.2
     Compiling orjson v3.5.2 (/tmp/pip-install-9p9zfq56/orjson_7d728d95dcd040108ffe70eedd910825)
     Compiling once_cell v1.7.2
     Compiling itoa v0.4.7
     Compiling inlinable_string v0.1.14
     Compiling associative-cache v1.0.1
     Compiling instant v0.1.9
     Compiling lock_api v0.4.3
     Compiling ahash v0.7.2
     Compiling parking_lot_core v0.8.3
     Compiling parking_lot v0.11.1
     Compiling serde_json v1.0.53 (/tmp/pip-install-9p9zfq56/orjson_7d728d95dcd040108ffe70eedd910825/local_dependencies/serde_json)
  error: could not compile `packed_simd_2` due to 14 previous errors
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit status: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --lib -- -C link-arg=-s`
  🔗 Found pyo3 bindings
  🐍 Found CPython 3.8 at /usr/local/bin/python
  error[E0557]: feature has been removed
     --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/lib.rs:205:5
      |
  205 |     const_fn,
      |     ^^^^^^^^ feature has been removed
      |
      = note: split into finer-grained feature gates


  error: attributes starting with `rustc` are reserved for use by the `rustc` compiler
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:43:7
     |
  43 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: attributes starting with `rustc` are reserved for use by the `rustc` compiler
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:37:7
     |
  37 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: attributes starting with `rustc` are reserved for use by the `rustc` compiler
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:31:7
     |
  31 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: attributes starting with `rustc` are reserved for use by the `rustc` compiler
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:25:7
     |
  25 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: attributes starting with `rustc` are reserved for use by the `rustc` compiler
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:19:7
     |
  19 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: attributes starting with `rustc` are reserved for use by the `rustc` compiler
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:13:7
     |
  13 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: cannot find attribute `rustc_args_required_const` in this scope
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:43:7
     |
  43 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: cannot find attribute `rustc_args_required_const` in this scope
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:37:7
     |
  37 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: cannot find attribute `rustc_args_required_const` in this scope
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:31:7
     |
  31 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: cannot find attribute `rustc_args_required_const` in this scope
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:25:7
     |
  25 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: cannot find attribute `rustc_args_required_const` in this scope
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:19:7
     |
  19 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: cannot find attribute `rustc_args_required_const` in this scope
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.4/src/codegen/llvm.rs:13:7
     |
  13 |     #[rustc_args_required_const(2)]
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^


  error: aborting due to 13 previous errors


  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/usr/local/bin/python', '--manylinux=off', '--strip=on'] returned non-zero exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for orjson

**Comment by cydergoth** [comment]
`FROM  tiangolo/meinheld-gunicorn-flask:python3.8-alpine3.11 as base

ENV PATH=/root/.cargo/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV PYTHONPATH="/var/www"

# Add a couple of useful things
RUN apk --no-cache --update add bash openssl-dev libffi-dev postgresql-dev --virtual build-dependencies build-base gcc wget curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN rustup toolchain install nightly
RUN rustup default nightly

# Setup some context
ENV METRICS_DEBUG false

# Tell docker where we want to work in the image
# /var/www is the default location for Web based content
WORKDIR /var/www

# Copy our python requirements file into the image and install
# the required libraries
COPY ./licenses/requirements.txt /var/www/requirements.txt
RUN pip install --upgrade pip
RUN pip install --upgrade --force-reinstall cffi
RUN pip install -r /var/www/requirements.txt`

**Comment by AdamBrianBright** [comment]
I'm not sure if I should mention this, but you may want to reconsider using Alpine for Python images
> [Don't use Alpine for Python images](https://pythonspeed.com/articles/alpine-docker-python/)
I myself had lot of troubles using python on alpine, despite amazing behaviour of other images.

**Comment by cydergoth** [comment]
That's certainly interesting as it seems to be recommended for Flask deployment with the above base image. 

Changing this to a doc bug to indicate that this library is not expected to compile under Alpine would would acceptable.

**Comment by anoduck** [comment]
As irritating as it is, this here explains my difficulties as well. #328 I have noticed an increasingly large number of projects are built exclusively only supporting main stream Linux distributions, often favor closed source windows and Apple, while ignoring support for Unix/BSD/Haiku/Musl. In the case of this package, I am sure it was not intentional, irritating, but just a consequence of conditions. Thanks, for the heads-up.
