### ISSUE TITLE
Cargo, the Rust package manager, is not installed or is not on PATH.

### ISSUE THREAD

**Issue by ahopkins** [ijl/orjson#192]
Since the last release, I am seeing errors in our build pipeline. Does the latest release not include a wheel?

```
ERROR: Command errored out with exit status 1:
 command: /path/to/.tox/py38/bin/python /path/to/.tox/py38/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp1l_pmzjj
     cwd: /tmp/pip-install-n7zcooxw/orjson
Complete output (6 lines):

Cargo, the Rust package manager, is not installed or is not on PATH.
This package requires Rust and Cargo to compile extensions. Install it through
the system's package manager or via https://rustup.rs/

Checking for Rust toolchain....
----------------------------------------
```

**Comment by ijl** [comment]
You likely need pip>=20.3 for manylinux_2_24. The previous recommendation was pip>=19.3. manylinux2014 jobs began erroring and were upgraded.

**Comment by alirezadaghigh99** [comment]
could you solve your problem? I have same issue

**Comment by jdarguello** [comment]
As a record, changing Python version of 32 bits to 64 bits solved this problem.

**Comment by edd313** [comment]
Solved the same problem by moving from Python 32 to 64 bits

**Comment by AsifRasool573** [comment]
i had the same issue, I updated the pip but it didn't work. I then check and I had Python 3.9 (32-bit). I changed it to the 64bit and my problem is solved.

**Comment by Ayten-web** [comment]
> i had the same issue, I updated the pip but it didn't work. I then checked and I had Python 3.9 (32-bit). I changed it to the 64bit and my problem is solved.

Hello. How did you do that, chancing 32 bit to 64 bit??

**Comment by ZOJulian** [comment]
I changed it from 32 bit to 64 but it didn`t change my Problem

**Comment by sanjay-gatti** [comment]
I have the same issue even though my python is 64 bit

**Comment by btseytlin** [comment]
Same issue out of nowhere, Mac M1

**Comment by suwaaaa** [comment]
maybe we should install Rust by ourselves. 
(https://doc.rust-lang.org/cargo/getting-started/installation.html ) 
and I'm trying ... now

**Comment by WolfgangFahl** [comment]
Why is this closed? The problem still happens with Python 3.10.8 on Mac OS 10.13.6.

**Comment by shivam221098** [comment]
Same problem on macOS 14.1

**Comment by hmda77** [comment]
I deleted Mysys from my computer and the problem solved

**Comment by Chist-Sergey** [comment]
Same issue on Mac OS 10.14.6

**Comment by Kittensx** [comment]
Same issue with Python 3.13.0, 64 bit, Windows 11

**Comment by BoatNg** [comment]
My system is Mac OS 10.14.6, and I solved this problem by installing Rust. `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
