### ISSUE TITLE
Missing wheel for CentOS 7

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [ijl/orjson#193]
OS: CentOS 7

In the 3.6.1 change to `manylinux_2_24`, CentOS 7 x86 wheel support was dropped. CentOS 7 supports `manylinux2014`/`manylinux_2_17` but not `manylinux_2_24`. `aarch64` support for `manylinux2014` still exists because the build lines for 3.9/8/7/6 were not updated with the container.

I've currently solved this issue by pinning orjson < 3.6.1.

**Comment by DavidWalz** [comment]
3.6.1 also does not have wheel support for Ubuntu 20.04

**Comment by petrprikryl** [comment]
Try to upgrade `Pip` to the latest version https://github.com/pypa/manylinux#manylinux

**Comment by falkben** [comment]
> Try to upgrade `Pip` to the latest version https://github.com/pypa/manylinux#manylinux

The issue is not with pip, it's that on systems with an older version of glibc (for us it's RHEL7) it's too old for the wheel.

I'm curious if this project could continue to publish wheels in future releases for older glibc?

**Comment by ijl** [comment]
I've published manylinux 2014 wheels by pinning the build to a month-old image. The error on newer images is "error: linker `cc` not found" and something else may eventually break.

**Comment by seweissman** [comment]
manylinux_2_17 should also work for RHEL7 (and most likely Centos 7) if that can be built more easily than manylinux 2014.
