### ISSUE TITLE
Custom deserializing, a different approach (w/Flask as motivator)

### ISSUE THREAD

**Issue by itamarst** [ijl/orjson#195]
Hi,

@hynek was [attempting to use orjson with Flask, and failed](https://stackoverflow.com/questions/60296197/flask-orjson-instead-of-json-module-for-decoding#comment121377506_63516680): Flask has a tagging system for serializing/deserializing JSON, and because of `orjson`'s lack of `object_hooks` the deserialization has to happen outside of `orjson` (this is the code: https://github.com/pallets/flask/blob/main/src/flask/json/tag.py#L312).

There are some API impediment mismatches in the Python layer, but let's assume those are solvable, and take a look at the big picture problem:

1. `orjson` provides better security and performance than default `json` in Python.
2. Flask is used at massive scale (50M+ downloads/month from PyPI).
3. Speeding up Flask JSON handling therefore would save significant CO2, money, and time.
4. It would likely also improve security for these applications.
5. But, it's quite hard to in a performant manner due to `orjson`'s limits on deserialization. Post-processing in Python is of course possible, but that would undermine the performance benefits; it'd be much faster to do it in the initial deserialization pass inside `orjson`.

So assuming this is something worth solving, let's consider some solutions:

1. Adding `object_hooks`. Per the FAQ you don't want to have `object_hooks`, but in theory you could reconsider it given the impact. Even if it did exist, however, calling into Python would still be slow, and I imagine the implementation would be much harder, and possibly much slower for everyone even when not using this feature.
2. Add a Rust-level hook, where you plug in an object implementing a trait (either as an `Box<dyn>` argument, or even as a generic). Now we're in a place where custom deserialization is both reliable and much faster since it's written in Rust, and likely the impact on users not using this feature is smaller, plausibly even imperceptible. This couldn't be used from Python without a lot more work, the default interaction would require compiling more Rust code.

So let's say the deserializer has a hook that is purely a Rust API. How would people use it?

* `orjson`, or at least the deserialization API, also gets published as a crate. 3rd party developers can then make their own custom `loads()` function for their particular application by creating their own Rust package that relies on `orjson`.
* Alternatively, or in addition, `orjson` could include custom `loads` functions for highly impactful use cases like Flask, e.g. `orjson.loads_flask()`.

This is just one approach, there may well be other solutions.

**Comment by itamarst** [comment]
I guess implicitly that's actually two solutions:

1. Provide generic hook.
2. Just write some custom code for Flask.

**Comment by ijl** [comment]
Well, it's possible. I would look at using an `object_hook` parameter on the public Python API. This doesn't preclude your hook being in a compiled language and vectorcall seems fast enough. I see PyDict as <5% of time taken on twitter.json. json also has an `object_pairs_hook` and prefers it to `object_hook`, but `object_hook` is maybe more used for being older, less disruptive to implement, and that <5% is probably faster than a call per pair. To look at it further I suggest coming up with a separate `test/test_object_hook.py` or the like showing usage and criteria.

**Comment by MaxTranced** [comment]
Was this done? Is there any documentation on how to develop an `ORJSONDecoder` and `ORJSONEncoder` like the ones needed here? https://stackoverflow.com/questions/60296197/flask-orjson-instead-of-json-module-for-decoding

**Comment by davidism** [comment]
Flask 3.0.1 is now available on PyPI. You can use the [flask-orjson](https://pypi.org/project/flask-orjson/) extension to quickly set up integration between Flask and orjson.
