### ISSUE TITLE
Unable to serialize OrderedDict

### ISSUE THREAD

**Issue by wzhliang** [ijl/orjson#20]
When encoding object that contains an OrderedDict, orison complains about `orjson.JSONEncodeError: Type is not JSON serializable: collections.OrderedDict`. json from standard library works fine.

 Python 3.7.3 on MacOS

**Comment by ijl** [comment]
Yes, this is intended. You can use a `default` function which checks `issublcass(obj, dict)` and returns `dict(obj)`.

**Comment by wzhliang** [comment]
OK.
