### ISSUE TITLE
orjson.JSONDecodeError: recursion limit exceeded

### ISSUE THREAD

**Issue by void4** [ijl/orjson#201]
I'm trying to deserialize a deep comment tree and I get a

```
    return orjson.loads(data.encode("utf8"))#is encode required?
orjson.JSONDecodeError: recursion limit exceeded at line 1 column 30404: line 1 column 29571 (char 29570)

```

error

Is there an argument I can give to orjson.loads so it can exceed the limit or is this hardcoded in this library?

**Comment by ijl** [comment]
This isn't configurable. Something like rapidjson may support deeper nesting.

**Comment by khanfarhan10** [comment]
Please have a look if this could be supported in the upcoming versions!
