### ISSUE TITLE
Adding OPT_TIMESTAMP

### ISSUE THREAD

**Issue by Mifour** [ijl/orjson#203]
Is the option to serialize/deserialize datetimes as POSIX timestamp somewhere in the roadmap? I'm considering implementing it although pyo3's PyDateTime_CAPI does not implement it.

**Comment by ijl** [comment]
The escape hatch for non-RFC 3339 strings is `OPT_PASSTHROUGH_DATETIME`. I don't think it's worth adding the complexity for this. In particular handling leap time and timezone conversion is an enormous burden.
