### ISSUE TITLE
[Feature Request] Support for parsing a sequence of JSON blobs

### ISSUE THREAD

**Issue by akvadrako** [ijl/orjson#204]
I am using orjson through most of my app, but there is one place where I end up having to use the stdlib json parser and that's when I'm consuming a sequence of blobs, like this:

```json
{"x": 1}
{"y": 2}
```

This is because the stdlib `decoder.raw_decode()` method returns the parsed object and an index, which indicates the last byte of the input data that was read. This allows the parser to be run again on the remaining data in the input.

Would it be possible to add something like the index return value to orjson?

**Comment by ijl** [comment]
This looks like NDJSON. If you have full control of reading the input you probably want to read into a buffer, find all \n, and pass a memoryview of each segment into loads. I don't think passing an index back is a usable API.

**Comment by akvadrako** [comment]
This isn't NDJSON so `'\n'` isn't relevant. I'm not saying the index is an ideal API, but it's makes this use case possible. As it is orjson just can't be used in this case.
