### ISSUE TITLE
Would you support parse float into Decimal?

### ISSUE THREAD

**Issue by yihuang** [ijl/orjson#21]
Really need a json library support Decimal and faster than the one in standard library.

**Comment by ijl** [comment]
There is no extension/C API for decimals. The library cannot avoid creating a float before calling the Decimal constructor. I suspect this should this be done by a schema/validation library on the output of loads().

**Comment by yihuang** [comment]
But if convert to float before passing to Decimal, it's already too late.
The only way is pass the raw string to Decimal, it can only be done by low level implementation.
We can support the ``parse_float`` callable argument like what std json library did:

```
>>> Decimal(json.loads('0.3'))
Decimal('0.299999999999999988897769753748434595763683319091796875')
>>> json.loads('0.3', parse_float=Decimal)
Decimal('0.3')
```

**Comment by ijl** [comment]
I see now. This can't support that.

**Comment by yihuang** [comment]
@ijl Maybe we can have an option to parse float into str, the user still has the chance to convert it into ``Decimal`` manually when needed.

**Comment by pjz** [comment]
IIRC, the latest (3.3+) decimal impl in the stdlib is actually in C, based on the cdecimal module ( https://pypi.org/project/cdecimal ), if that changes anything.

**Comment by pjwerneck** [comment]
For a project that prides itself on serializing everything correctly, this is a really serious shortcoming, since it prevents using the library on finance-related APIs. Even if you can't create a Python decimal in the C code, at the very least there should be an option to deserialize JSON numbers as string to avoid losing precision on the float conversion.

**Comment by anydasa** [comment]
Hi,

This isn't an orjson issue but a common Python challenge. The problem arises when converting a float directly to Decimal, leading to precision loss. The correct approach is to convert from a string to Decimal.

```python
Decimal(str(0.01))
```

Here's a workaround using orjson:

```python
from dataclasses import fields
from decimal import Decimal
from enum import Enum
from typing import Type, TypeVar
from orjson import orjson

T = TypeVar('T', bound='ModelSerializerJson')

class ModelSerializerJson:
    def to_json(self):
        return orjson.dumps(self)

    @classmethod
    def from_json(cls: Type[T], string: str) -> T:
        data = orjson.loads(string)
        for field in fields(cls):
            if issubclass(field.type, Decimal):
                data[field.name] = Decimal(str(data[field.name]))
        return cls(**data)

```

This code ensures Decimal fields are correctly handled by converting JSON fields to strings, then to Decimal, maintaining precision.

Hope this helps!

**Comment by FeldrinH** [comment]
> Here's a workaround using orjson:
> 
> ```python
> from dataclasses import fields
> from decimal import Decimal
> from enum import Enum
> from typing import Type, TypeVar
> 
> from orjson import orjson
> 
> class ModelSerializerJson:
>     def to_json(self):
>         return orjson.dumps(self)
> 
>     @classmethod
>     def from_json(cls, string: str):
>         data = orjson.loads(string)
>         for field in fields(cls):
>             if issubclass(field.type, Decimal):
>                 data[field.name] = Decimal(str(data[field.name]))
>         return cls(**data)
> ```
> 
> This code ensures Decimal fields are correctly handled by converting JSON fields to strings, then to Decimal, maintaining precision.
> 
> Hope this helps!

This doesn't actually work. It appears to work in some cases because calling `str` on a float can in some cases produce a representation of the float with fewer decimal places. However, the values are still converted to floats during parsing, which loses precision.

For example
```python
@dataclass
class Test(ModelSerializerJson):
    value: Decimal

print(Test.from_json('{"value": 0.123456789123456789123456789123456789}'))
print(Test(Decimal('0.123456789123456789123456789123456789')))
```
prints
```
Test(value=Decimal('0.12345678912345678'))
Test(value=Decimal('0.123456789123456789123456789123456789'))
```
(Notice that in the first case most of the decimal places have been cut off, because a float can't accurately represent them.)

**Comment by Telofy** [comment]
We're working with currencies, so this is the one critical feature for us that I'm looking for in each JSON library.
