### ISSUE TITLE
Decoding large JSON leads to KILLED

### ISSUE THREAD

**Issue by michaeldorner** [ijl/orjson#210]
I have encountered some problems with orjson (most recent version) and decoding large JSON files (20 or 30 GB): the scripts crash and get killed. The JSON files contain timestamps and strings if this helps. Encoding is not an issue.

**Comment by ijl** [comment]
If you can isolate this to a specific suspicion about orjson's implementation I could look. It's not obvious this isn't a normal OOM. Python will use some multiple of your file's size in the end (e.g.,`str` are worst case 4 bytes per char).
