### ISSUE TITLE
Memory Leak In Orjson

### ISSUE THREAD

**Issue by zoneadm** [ijl/orjson#211]
We are using orjson with an AWS Kinesis Consumer (running 3 instances of the consumer on one EC2 instance). The consumer processes about 800000 Records / hour with an average lengths of 2200 bytes. A few month ago we switched back from orjson 3.5.2 to ujson 4.0.2 because of memory problems on the instance, leading to oom-reaper killing the consumer processes. Memory data can be seen here:
![orjson-ujson](https://user-images.githubusercontent.com/7266837/135042462-30fa0022-610f-48af-b33a-2d6b7e503ce4.png)

Now we tried orjson 3.6.2 again and switched back from ujson to orjson. Unfortunately, there seems still to be a significant memory leak. Memory data can be seen here: 
![ujson-orjson](https://user-images.githubusercontent.com/7266837/135042236-412d6e16-399a-4524-b63f-0535a31a05e3.png)

**Comment by ijl** [comment]
Can you describe in detail the usage? I can't reproduce this.

**Comment by ijl** [comment]
See if https://github.com/ijl/orjson/releases/tag/3.6.4 fixes it and reopen if not please.

**Comment by zoneadm** [comment]
Updated to orjson 3.6.4 this morning and running it now. I will report here the result within the next 2 days. Hopefully it fixed it. In general: great work you are doing with orjson.

**Comment by enuk1dze** [comment]
We had the same problem. Update from `orjson~=3.5.1` to `orjson~=3.6.4` helped.
