### ISSUE TITLE
installation with setup.py

### ISSUE THREAD

**Issue by ramezanifar** [ijl/orjson#218]
I download the latest version. 
Then, I install with:
`sudo python3 setup.py install`
Installation completes but when I import it, it is not found:
```
>>> import orjson
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'orjson'
```
When I check the version with:
`pip3 freeze`
it shows the version as:
`orjson==0.0.0`

Why is the version zero?

Thanks

**Comment by johnthagen** [comment]
It looks like OrJSON uses `maturin` build system:

https://github.com/ijl/orjson/blob/02d6805af278493f657c17305a2f0cc054f04078/pyproject.toml#L5-L8

This `setup.py` file should probably be removed from this repo?

By the way, `setup.py install` is deprecated. See this article for the alternatives: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
