### ISSUE TITLE
Cannot install orjson 3.6.4 on Debian 10.

### ISSUE THREAD

**Issue by hardpoorcorn** [ijl/orjson#219]
# pip3 install orjson
Collecting orjson
  Using cached https://files.pythonhosted.org/packages/f6/1e/61225fb33a9f614ac67f595a80008ded0bdc58ea20c0201703a166d37fca/orjson-3.6.4.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-krpawaz1/orjson/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-krpawaz1/orjson/

**Comment by DanNduati** [comment]
experiencing the same issue:
Using cached https://files.pythonhosted.org/packages/92/97/895dfe0c2e7820fd5453d0efab6a9036de7f97b4edfd157a6a414dd3b0ee/orjson-3.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-na2e123s/orjson/setup.py'
    
    ----------------------------------------

**Comment by DanNduati** [comment]
@hardpoorcorn  Solved this by upgrading pip ```pip install --upgrade "pip>=20.3"``` and running the install again ```pip install --upgrade orjson```
