### ISSUE TITLE
Reading json file using orjson package

### ISSUE THREAD

**Issue by Martin20494** [ijl/orjson#225]
Hi team,

Could you please help me with how to read json file with orjson? I tried below but it asked for byte type for input. Thank you very much.

```
import orjson

f = open(<file.json>, "r")
a = orjson.load(f)
```

**Comment by akx** [comment]
`orjson.loads()` indeed accepts bytes, so you'll need to read those bytes in and pass them to orjson.

```
import orjson

with open("file.json", "rb") as f:
  a = orjson.loads(f.read())
```

**Comment by zhechao1-intel** [comment]
import orjson
    import json5
    
    if __name__ == '__main__':
        with open('file.json', 'rb') as f:
            data = orjson.loads(f)

error:orjson.JSONDecodeError: Input must be bytes, bytearray, memoryview, or str: line 1 column 1 (char 0)
