### ISSUE TITLE
src/deserialize/error - maybe don't panic?

### ISSUE THREAD

**Issue by ericabrauer** [ijl/orjson#226]
Using orjson loads in Python3.8 in a multiprocessing queue, program gets hung up with the following output: 

```
thread '<unnamed>' panicked at 'byte index xxx is not a char boundary; it is inside '{random Chinese character}' (bytes xxx..xxx) of '{string of text}'[...]', src/deserializ/error.rs:43:39
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace
```

I ran with the RUST_BACKTRACE=1 and it returned nothing new but told me to use RUST_BACKTRACE=full, when I did that it overwhelmed my screen with over 100k lines of the same random string of characters. 

I thought that the issue was the Chinese character but I tested and it doesn't appear to be an issue with orjson.loads locally. I'm not sure how to replicate and the error message doesn't provide much detail. [This link](https://dev.to/senyeezus/ergonomic-error-handling-with-rust-13bj) talks about using an `expect` method though I'm not sure if that's already been implemented here (I know almost nothing about Rust). 

According to the responses on [this SO question](https://stackoverflow.com/questions/67328721/handling-panics-of-external-libraries), it appears this should be raised as an issue here.

**Comment by Stranger6667** [comment]
I was able to reproduce the issue with the following snippet:

```python
import orjson

orjson.loads(b'"\xc8\x93\xc3\x8c')
```

Fails with:

```
⇒  python example.py
thread '<unnamed>' panicked at 'byte index 4 is not a char boundary; it is inside 'Ì' (bytes 3..5) of `"ȓÌ`', src/deserialize/error.rs:44:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    39341 abort (core dumped)  python
```

orjson 3.6.5, Python 3.9.9 on Linux archlinux 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux

Found while generating data with Hypothesis strategy. Here is the test that helped me to find the failing example:

```python
from hypothesis import strategies as st, given, settings
import orjson


@given(st.binary())
@settings(max_examples=100000)
def test_loads(value):
    try:
        orjson.loads(value)
    except orjson.JSONDecodeError:
        pass
```

The actual use case is to generate bytes that are not valid JSON values (I build a [service](https://schemathesis.io/) that generates test data for web APIs):

```python
from hypothesis import strategies as st


def is_invalid_json(value: bytes) -> bool:
    try:
        orjson.loads(value)
        return False
    except ValueError:
        return True

non_json = st.binary().filter(is_invalid_json)
```

**Comment by Stranger6667** [comment]
I guess, that the solution would be to use `chars` and apply `skip` instead of indexing into `s`

**Comment by Stranger6667** [comment]
Intuitively I'd assume that `s.char_indices().take_while(|(idx, _)| *idx < self.column).count()` should work - count chars which indices are before the column, but unfortunately it doesn't :(

**Comment by Fogapod** [comment]
```python
import orjson


orjson.loads('"\xc8')
```
is enough to cause panic:
```
thread '<unnamed>' panicked at 'byte index 2 is not a char boundary; it is inside 'È' (bytes 1..3) of `"È`', src/deserialize/error.rs:44:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort (core dumped)  python
```
though bytes do not panic for the same input:
```python
>>> orjson.loads(b'"\xc8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
orjson.JSONDecodeError: str is not valid UTF-8: surrogates not allowed: line 1 column 2 (char 1)
```

**Comment by ijl** [comment]
Fixed in https://github.com/ijl/orjson/releases/tag/3.6.6, thanks @akx.
