### ISSUE TITLE
orjson build recently broken

### ISSUE THREAD

**Issue by rosscdh** [ijl/orjson#227]
Hi there,

it seems the most recent release has broken previously working builds

```
     Compiling orjson v3.6.5 (/tmp/pip-install-9eatd36n/orjson_52649607827e443bb296f39d214384b3)
      Finished release [optimized] target(s) in 1m 21s
  💥 maturin failed
    Caused by: Failed to execute 'patchelf', did you install it?
    Caused by: No such file or directory (os error 2)
  🔗 Found pyo3 bindings
  🐍 Found CPython 3.9 at /venv/bin/python
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/venv/bin/python'] returned non-zero exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for orjson
```

no change to packages in over a month...

docker build fails on mac as well as linux builds

**Comment by rosscdh** [comment]
Seems some upstream dependency has broken

I added `patchelf` to the apt install and were back in action

**Comment by bluebrown** [comment]
Strange part is that my docker build didn't even fail. But running image failed because it couldn't import orjson, since it was never installed.
