### ISSUE TITLE
JSON5 Format Support

### ISSUE THREAD

**Issue by Vioshim** [ijl/orjson#229]
Well the current issue more of an issue is an actual feature request or suggestion.

But basically, I've been wondernig if JSON5 is going to be implemented in this library which I think it'd be very useful given the library's speed performance in reading operations while being able to keep the advantages that this new format provides.

Have a great day, looking forward your response, cheers.

**Comment by ijl** [comment]
It would be a different implementation and different API. For example, compare ruamel.yaml and PyYAML. The former returns wrapper objects to preserve comments etc. It won't be supported in this library.
