### ISSUE TITLE
Is Rust nightly still necessary, or can you use some released version of Rust?

### ISSUE THREAD

**Issue by itamarst** [ijl/orjson#23]
I will need to package `orjson` for Conda-Forge if I decide to use it, and I'm not sure if random versions of rust will be available.

**Comment by ijl** [comment]
nightly is not quite a pre-release, it's a version with non-stable features enabled. The nightly version required doesn't generally change. Conda Forge's versions of stable and nightly are both badly out of date, but if upgraded would be fine. Tracking for using stable is https://github.com/PyO3/pyo3/issues/5.

**Comment by ijl** [comment]
For example, I just built 2.0.6 on `nightly-2019-02-28`.

**Comment by itamarst** [comment]
Conda-Forge has 1.36 (https://anaconda.org/conda-forge/rust), which seems to be latest stable release. But rust-nightly sounds like it's still work in progress: https://github.com/conda-forge/rust-feedstock/issues/31

**Comment by ijl** [comment]
I see, thanks. I was looking at https://anaconda.org/anaconda/rust at 1.29.0.

**Comment by itamarst** [comment]
`conda-forge` channel tends to be more up-to-date package channel than `anaconda` channel, I think. (The former is community-driven, the latter is managed by Anaconda Inc).

**Comment by ijl** [comment]
There are now source distributions, and maybe that makes it easier to package for Conda. Please reopen if there's something to do about packaging.

**Comment by EntPyle** [comment]
Would just like to provide notice that orjson is packaged for Linux on conda-forge. I am still working on the osx and windows versions. Any help there would be appreciated

**Comment by rominf** [comment]
https://github.com/PyO3/pyo3/issues/5#issuecomment-647094806 states that stable Rust is supported.

Any chance to support Rust stable? I'm trying to build a package for Fedora 33, and I'm blocked on this.
