### ISSUE TITLE
Automatically serialize `pathlib.Path`

### ISSUE THREAD

**Issue by UmbralReaper** [ijl/orjson#230]
`pathlib.Path` is part of the Python standard library and it would be nice to serialise it by default.

**Comment by ijl** [comment]
I think it's probably not commonly used enough to justify being serialized natively.

**Comment by indigoviolet** [comment]
@ijl would you reconsider this in 2023? I notice for example that Pydantic can serialize Paths.

**Comment by rgacote** [comment]
Additional request to reconsider in 2024. I'm doing dictionary exports of Excel worksheets containing images. Each image has a PosixPath associated with it. Would be useful to serialize str(PosixPath).
