### ISSUE TITLE
An option to escape unicode

### ISSUE THREAD

**Issue by Tinche** [ijl/orjson#232]
Hi,

great library.

Right now I'm using ujson for my log serialization due to them supporting `ensure_ascii`, and I'm logging user-generated data (request parameters).

The issue with logging is it usually involves a complex pipeline that's outside of my control. For example for us it's Python/structlog -> stderr -> a file through the Kuberentes Docker logging driver -> a pod from the FluentBit daemonset -> ElasticSearch. Outputting pure unicode, which technically correct, is just asking for trouble and leads to issues like https://github.com/fluent/fluent-bit/issues/4377.

So I'd like an opt-in flag to just output characters in the range of pure ASCII, to better support the logging scenario. What do you think?

**Comment by ijl** [comment]
I don't think this would be a trivial thing to implement and obviously it's just not appealing. I don't think you get around having a working UTF-8 locale at this point. If you can't fix that I suggest using python-rapidjson.
