### ISSUE TITLE
datetime.timedelta support via flag

### ISSUE THREAD

**Issue by vdwees** [ijl/orjson#234]
I would like it if orjson supported datetime.timedelta serialization via a flag, would a PR be welcome? I am thinking it would serialize to a float in seconds, something like this:
```python
>>> import orjson, datetime
>>> orjson.dumps({"offset": datetime.timedelta(seconds=10.1)}, option=orjson.OPT_SERIALIZE_TIMEDELTA)
b'{"offset":10.1}'
```

**Comment by ijl** [comment]
ISO 8601 has a way to specify duration. I think that standard would be the thing to implement. If someone would like to implement it try the documentation first in this issue, then tests.

**Comment by vdwees** [comment]
I've worked with [ISO 8601 Duration strings](https://en.wikipedia.org/wiki/ISO_8601#Durations), but I don't think they are the best option in this case.

Duration strings are most useful when specifying periods like years and months, something timedelta cannot represent. On the other hand, timedelta can represent very small durations, like microseconds. Because very few languages support parsing duration strings in their standard libraries, there is a range of variability in how durations are parsed, especially small durations, and custom parsing logic is prevalent. On the other hand, representing a duration as a number in seconds aligns with S.I./metric standards, completely avoids the parsing issue, and there can be a 1:1 relationship with a timedelta and a json number.

That said, I can see the appeal of using ISO 8601, given that orjson already uses it for serialising datetime. It would make sense to add it, if only for consistency. If there was a PR to add support for timedelta, optionally represented as either a JSON number (S.I. units) or as a string (ISO 8601), would that be acceptable?

**Comment by ijl** [comment]
Hm, ok, if there isn't an obvious standard, then a convenience reason for automatically serializing timedelta isn't that clear to me. There is also a performance reason to include something, and I'm not sure that's your motivation and if it would be a meaningful difference. If you were willing to serialize both, sure. But I don't know much about this and don't want to maintain it, so for me the bar would be something like tens of tests obviously testing against the spec and min/max/edge cases. I suggest starting with documentation for the options in markdown, here, matching the README format.

**Comment by zevisert** [comment]
One thing that might bring a lot of extra interest to the ISO-8601 Duration format is the (now) stage 3 proposal for the Temporal API in javascript. In it's current form, the API prefers ISO-8601 durations for serialization. 

https://tc39.es/proposal-temporal/docs/duration.html
