### ISSUE TITLE
Could you create a document about how to use orjson?

### ISSUE THREAD

**Issue by binbjz** [ijl/orjson#237]
A good project should have a detailed document. I think everyone who wants to use it needs this document.

**Comment by akx** [comment]
You can find usage documentation in the README. https://github.com/ijl/orjson#usage

**Comment by binbjz** [comment]
> You can find usage documentation in the README. https://github.com/ijl/orjson#usage
This is a usage guide and there is no real API documentation.

**Comment by binbjz** [comment]
> 

This is a usage guide and there is no real API documentation
