### ISSUE TITLE
`JSONEncodeError` inconsistency

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ijl/orjson#238]
According to the documentation:

> [`JSONEncodeError` is a subclass of `TypeError`. This is for compatibility with the standard library.](https://github.com/ijl/orjson/blob/c196f0e55bd51d3693d381ccc06f2fd4b5443d86/README.md?plain=1#L173-L174)

The `orjson.pyi` code also suggests this:

https://github.com/ijl/orjson/blob/c196f0e55bd51d3693d381ccc06f2fd4b5443d86/orjson.pyi#L13

However, in the actual implementation (?), it is simply an alias of `TypeError`:

https://github.com/ijl/orjson/blob/c196f0e55bd51d3693d381ccc06f2fd4b5443d86/src/typeref.rs#L148

And indeed:

```bash
> python3 -c 'import orjson; print(orjson.JSONEncodeError is TypeError)'
True
```

Now, technically, a class is considered a subclass of itself per [the documentation of `issubclass`](https://docs.python.org/3/library/functions.html#issubclass). However, I'd argue that most people wouldn't think of it that way when reading the orjson documentation, and the `orjson.pyi` line is definitely inconsistent with that (though I'm not familiar enough with this project's structure to understand what its significance is, anyway).

**Comment by ijl** [comment]
It's documented as a subclass and behaves as if it is. I don't see an actionable proposal.
