### ISSUE TITLE
Question: Skip dataclass properties with None values in serialization. Is it possible?

### ISSUE THREAD

**Issue by jdvor** [ijl/orjson#239]
Is it possible to skip dataclass properties with `None` value in serialization **without** OPT_PASSTHROUGH_DATACLASS and writing custom serialization outside orjson?

```python
import orjson
from dataclasses import dataclass
from typing import Optional

@dataclass
class MyDto:
    name: str
    age: Optional[int] = None

dto = MyDto("John Doe")
js = orjson.dumps(dto).decode("utf-8")
print(js)
```

So the result of the above would be: `{"name":"John Doe"}` rather than `{"name":"John Doe","age":null}`

**Comment by ijl** [comment]
#123, I don't think anyone is interested in taking it on.

**Comment by jdvor** [comment]
It's pity, because sparse contracts are quite common use case.

**Comment by RuABraun** [comment]
Would just like to register my interest in this feature!
