### ISSUE TITLE
Building from source requires a `python` executable in the PATH

### ISSUE THREAD

**Issue by dmrlawson** [ijl/orjson#240]
Hi,

I was trying to install `orjson` in a Pyston virtualenv on a system that has no `/usr/bin/python` (since it only has Python3 installed).

Pyston wants to build everything from source but it was failing with this:

```
  error: failed to run custom build command for `orjson v3.6.6 (/tmp/pip-install-tru9cq9v/orjson_f087531780034de7a8fd9449438c396c)`

  Caused by:
    process didn't exit successfully: `/tmp/pip-install-tru9cq9v/orjson_f087531780034de7a8fd9449438c396c/target/release/build/orjson-d83e90a79e049bc4/build-script-build` (exit status: 101)
    --- stderr
    thread 'main' panicked at 'python version did not print: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:7:10
```

I looked at `build.rs` and suspected it might be trying to run whichever `python` it finds on the path. I installed `python-is-python3` which gives a system `python` executable and the build succeeded. This seems unnecessary as `/usr/bin/python` then points to cpython3, whereas I was installing into a pyston virtualenv.

I was installing with `path_to_venv/bin/python -m pip install orjson` directly without "activating" the virtualenv. I suppose activating it might be another workaround, but usually packages work without needing to.

**Comment by ijl** [comment]
#241 fixed the issue of `python` being needed on `PATH`. I see pyston failing further on. It likely needs https://github.com/pyston/pyston/issues/144 and then its ABI tags supported in maturin.
