### ISSUE TITLE
Support for flattened JSON

### ISSUE THREAD

**Issue by gethvi** [ijl/orjson#246]
Let me start by saying huge thanks for this library!

Would it be possible to add option for loading/dumping a flattened JSON?

**Comment by tooptoop4** [comment]
also am interested in an equivalent of this:
https://stackoverflow.com/questions/54210389/is-there-a-generic-way-to-read-the-multiline-json-in-spark-more-specifically-sp

**Comment by ijl** [comment]
Flattened JSON is out of scope for this library.
