### ISSUE TITLE
ensure_ascii option in orjson?

### ISSUE THREAD

**Issue by skandabhairava** [ijl/orjson#247]
Let me first say this, this is probably my fav package. I'm gonna shift all my projects using json to orjson;

I've come across the "ensure_ascii" option in the normal json library. How do i do the same in orjson?? Is there an option for that? and if there is, how do I also use pretty print(INDENT 2) option, with that other option, thanks a lot :D!

**Comment by ijl** [comment]
This project outputs `bytes` and assumes UTF-8 will be handled correctly. That may not have been reasonable when `json` was added to Python 2. Probably it's only legacy now? It won't be supported.

"indent is replaced by option=orjson.OPT_INDENT_2 and other levels of indentation are not supported."
