### ISSUE TITLE
pylint error for orjson 

### ISSUE THREAD

**Issue by michaeldorner** [ijl/orjson#248]
`pylint` gives a `no-member` error for orjson: 

    Module 'orjson' has no 'loads' member

It must be a false-positive error since orjson works like a charm. Any ideas for an easy fix?

**Comment by ijl** [comment]
I've see pylint do that with extensions and I don't know of anything this project can do differently.

**Comment by michaeldorner** [comment]
Just for the stake of completeness: You can disable the warning for the line(s) you use `orjson` by the following comment:
   
    orjson.dumps(result)  # pylint: disable=maybe-no-member

**Comment by Lyapsus** [comment]
Problem persists

**Comment by dpinol** [comment]
Since I don't see any difference with other projects, I created pylint bug https://github.com/pylint-dev/pylint/issues/9762

**Comment by dk-coligo** [comment]
If using VSCode, suppress the warning with:
```
"pylint.args": [
        "--extension-pkg-allow-list=orjson",
    ],
```

**Comment by ozooner** [comment]
Can be fixed by whitelisting `orjson` to your .pylintrc file
`extension-pkg-whitelist=orjson`

**Comment by philip4096** [comment]
Or
```toml
[tool.pylint]
extension-pkg-whitelist = ["orjson"]
```
in a `pyproject.toml` if you are using one.
