### ISSUE TITLE
orjson crashes on NaT value in numpy array

### ISSUE THREAD

**Issue by pvrba** [ijl/orjson#249]
orjson cannot handle `NaT` (aka `None`) values in numpy arrays of type `datetime64`. I Googled that the underlying Rust datetime library cannot handle datetimes before 1970.

To reproduce:
```
import numpy as np
import orjson
orjson.dumps(dict(times=np.datetime64('NaT')), option=orjson.OPT_SERIALIZE_NUMPY)
```
leads to:
```
thread '<unnamed>' panicked at 'byte index 4 is out of bounds of `<M8`', src/serialize/numpy.rs:728:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by ijl** [comment]
I've released 3.6.8 that handles this as an unsupported type. It seems like it could serialize as `null`, but no need now.
