### ISSUE TITLE
Document that 'bool' is a natively supported type

### ISSUE THREAD

**Issue by 2-5** [ijl/orjson#26]
The readme says: 

> It natively serializes `str`, `dict`, `list`, `tuple`, `int`, `float`, `datetime.datetime`, `datetime.date`, `datetime.time`, and `None` instances.

Notice that `bool` is missing from it. Because the list is so precise, I had to go look through the test suite to confirm that `bool` is indeed supported.

**Comment by ijl** [comment]
I've added this to the README in 65af45a5d24144ed050f6865f4881aae628a92c7. Thank you.
