### ISSUE TITLE
Can no longer install orjson in docker  container

### ISSUE THREAD

**Issue by moshfrid** [ijl/orjson#262]
Im not sure why, but the newest release (3.6.9) causes my pip install to fail saying cargo is not installed. If i install cargo, then maturin doesnt have the resolver feature enabled, 3.6.8 works without a problem.

**Comment by jose-reveni** [comment]
I´m having a similar issue, but in my case 3.6.9 works, but 3.7.0 doesnt!

**Comment by moshfrid** [comment]
You are correct, my mistake, the issue starts with 3.7.0
