### ISSUE TITLE
`dumps` sometimes output strange "corrupted" bytes objects

### ISSUE THREAD

**Issue by yvan-the-barbarian** [ijl/orjson#265]
# Issue
The `bytes` object output by dumps will sometimes fail with some operations, such as passing to `int` (almost always fails) or `float` (fails occasionally).

_We highly suspect the issue is that the memory location the bytes object points to is not null terminated. All random successes we had with `int` turned out to be accidentally null terminated._

# Example
``` python
from ctypes import string_at
from sys import getsizeof

import orjson

while True:  # Might take a few attemps to crash
    constant = b'1596728892'
    corrupted = orjson.dumps(1596728892)

    assert corrupted == constant  # Equality works
    assert list(corrupted) == list(constant)  # Enumerating works.

    # These all work.
    print(int(constant), '- Constant')
    print(int(bytes(list(corrupted))), '- Re-create from list')
    print(int(corrupted.decode().encode()), '- Decode then encode')
    print(int(corrupted[:-1]), '- Subset (remove last character)')
    print(int(corrupted[1:]), '- Subset (remove first character)')
    print(int(corrupted[::2]), '- Subset (skip characters)')
    print(int(corrupted[::-1][::-1]), '- Reverse twice')

    print(string_at(id(corrupted), getsizeof(corrupted)).hex())  # Memory location is not null terminated and could fail if used as a C-string.
    print(int(corrupted), 'Sometimes fails')  # But this will sometimes fail.
```

# Tested on
orjson: 3.6.7, 3.7.0
Python versions: 3.9.2, 3.9.8, 3.10.4
OS: Windows, Mac OS and Linux
Processor: All Intel Processors (but just because we didn't have anything else)

**Comment by ijl** [comment]
Thank you for the report. `PyBytesObject.ob_sval ` should be null-terminated. Fixed in https://github.com/ijl/orjson/releases/tag/3.7.1
