### ISSUE TITLE
Publish python3.10 manlinux_2_24 wheels

### ISSUE THREAD

**Issue by iwoloschin** [ijl/orjson#266]
Would it be possible to continue publishing python3.10 manylinux_2_24 wheels? Ubuntu 18.04 is still supported and very easy to install python3.10 on, but new releases of orjson currently do not provide a wheel that will work on Ubuntu 18.04.

Ubuntu 18.04 has [glibc 2.27](https://packages.ubuntu.com/source/bionic/glibc).

**Comment by rsb177** [comment]
Running into a similar issue with Amazon Linux 2.  highest manylinux AL2 supports is 2_26

**Comment by ijl** [comment]
Ok, I've published manylinux2014/manylinux_2_17 wheels for python3.10. manylinux_2_24 is apparently going end of life sooner than manylinux2014.

**Comment by rsb177** [comment]
@ijl, my CI runners thank you!
