### ISSUE TITLE
load(stream)

### ISSUE THREAD

**Issue by sbrandtb** [ijl/orjson#27]
Is there a reason orjson does not, should not or cannot support loading from streams (→ `load()` instead of `loads()`)

In my use case (big JSON rendered in Django Rest Framework), memory usage goes up by 60% when using orjson compared to the stdtlib and I suspect part of it being the cast to a bytestring:

```python
# this
orjson.loads(decoded_stream.read())
# instead of
orjson.load(decoded_stream)
```

**Comment by ijl** [comment]
It hasn't come up, but it can possibly be added. I see Django reading the entire body into an `io.BytesIO` object and rest_framework calling `json.load` with that. You suspect the difference is the contents being copied when creating a `bytes` object? (I don't know the implementation details there.) Is memory usage of orjson higher even if both use `bytes`? How large is the payload?

**Comment by sbrandtb** [comment]
When introducing a new JSON parser to Django Rest Framework, one needs to implement a new parser class. I did it like that:

```python
def default_serializer(obj):
    if isinstance(obj, Decimal):
        return float(obj)
    if isinstance(obj, str):
        return str(obj)
    if isinstance(obj, dict):
        return dict(obj)
    elif hasattr(obj, '__iter__'):
        return [item for item in obj]
    elif isinstance(obj, UUID):
        return str(obj)
    elif hasattr(obj, 'tolist'):
        return obj.tolist()
    elif hasattr(obj, '__getitem__'):
        cls = list if isinstance(obj, (list, tuple)) else dict
        try:
            return cls(obj)
        except Exception:
            pass
    raise TypeError


class ORJSONParser(BaseParser):
    """
    Parses JSON-serialized data.
    """
    media_type = 'application/json'
    renderer_class = ORJSONRenderer

    def parse(self, stream, media_type=None, parser_context=None):
        """
        Parses the incoming bytestream as JSON and returns the resulting data.
        """
        parser_context = parser_context or {}
        encoding = parser_context.get('encoding', settings.DEFAULT_CHARSET)
        try:
            decoded_stream = codecs.getreader(encoding)(stream)
            return orjson.loads(decoded_stream.read())
        except ValueError as exc:
            raise ParseError('JSON parse error - %s' % str(exc))
```

I have not spent much time into tracing all the details since it is just a suspicion that the memory usage goes up party because of this. The payload is around 50MB, memory usage with stdlib parser is around 360M, with orjson 576M

**Comment by ijl** [comment]
I think the difference in memory usage is just baseline. To deserialize `data/twitter.json.xz` (632KiB uncompressed), the growth in process memory usage after calling `loads()` on the fixture passing `str`:

json: 888KiB
orjson: 2772KiB
rapidjson: 5012KiB
simplejson: 1392KiB
ujson: 2444KiB

Passing `bytes`:

json: 1300KiB
orjson: 2332KiB
rapidjson: 5648KiB
simplejson: 2016KiB
ujson: 2732KiB

It may make sense to support reading io-like objects in `orjson.loads()` for convenience, though.

**Comment by ijl** [comment]
Memory usage aside, loading from a file-like object would be accepted if the tests are exhaustive.

**Comment by ijl** [comment]
@sbrandtb loads() memory usage was reduced in 2.0.10.

**Comment by Evpok** [comment]
@ijl Does closing this mean that you decided against ever including it or are you just cleaning up the issues? :-)

**Comment by sbrandtb** [comment]
@ijl I'm also interested in the reason. This is still valid for me. I would like to work on it, but I would need to learn rust and cPython API and that's quite a lot :confused:

**Comment by ijl** [comment]
The `stream` in the implementation above is an `io.BytesIO` object that has had the full request body read into it. There would no savings in reading chunks, only in not creating unnecessary copies of the data. There's no reason to add support for streams. 

The memory usage in the initial post is now lower, but some difference will remain from implementation differences.

The parser class above is just django-rest-framework slightly adapted, but just `orjson.loads(stream.getvalue())` would be sufficient and reduce memory usage by doing only one `bytes` copy rather than a conversion to `str` through `codecs`.

The least-copies implementation would be to support passing in `io.BytesIO.getbuffer()`, which is a `PyMemoryViewObject`. I doubt it would be used by the community enough to justify anyone's time and don't suggest implementing that, though.

**Comment by kshpytsya** [comment]
Do I understand it correctly that we should not hope to get support for reading from streams in orjson? My use case is loading json from compressed stream without requiring memory for entire uncompressed json. With stdlib's json I would do:

```py
import lzma

with lzma.open(input_file) as f:
   data = json.load(f)
```

**Comment by hhromic** [comment]
Same here, we also have a streaming use case. In our case, reading HTTP response payloads in aiohttp:
```python
from aiohttp import web

async def handle(request):
    data = json.load(request.content)
    return web.Response(text="OK")

app = web.Application()
app.add_routes([
    web.post("/handle", handle),
])
web.run_app(app)
```
