### ISSUE TITLE
Join forces with hyperjson?

### ISSUE THREAD

**Issue by mre** [ijl/orjson#3]
Hey there,
just found your repo. I'm the author of hyperjson, the other pyo3-based Python module for JSON. I was wondering whether we could join forces and merge both project. From my perspective, this would be beneficial for improving the compatibility with Python's JSON module. Also, we wouldn't have to do the performance work in two places.
We could merge both codebases in one central place.
What do you think?

**Comment by ijl** [comment]
I think this library is substantially complete, and the goals and implementations of the two libraries are incompatible, sorry.
