### ISSUE TITLE
dataclass support

### ISSUE THREAD

**Issue by ijl** [ijl/orjson#32]
I'd like to add support for `orjson.dumps()` to serialize dataclass instances.

This is a breaking change: users may rely on instances falling through to `default` and controlling how an instance is serialized. This would be version 3.

The [dataclasses documentation](https://docs.python.org/3/library/dataclasses.html) provides `field(metadata={...})` for third parties to customize. I'm not aware of standardized usage around this.

The use case I'm aware of right now is a user wanting to not serialize a value.

For that I think something like `attr: str = field(metadata={"serialize": False})`, and `orjson.dumps()`  requiring an `option=OPT_CUSTOM_DATACLASS` or such to have that take effect.

Without the need to inspect metadata, serializing a dataclass looks much like serializing a `dict`. The option is to avoid two additional method calls for metadata if customization isn't needed.

Feedback and use cases are welcome.

**Comment by prostomarkeloff** [comment]
LGTM. Dataclasses it is a pretty feature in python3.7+.

**Comment by ijl** [comment]
This is implemented on master, without customization by metadata, and to be released in 3.0.0.

**Comment by ijl** [comment]
This was released in 2.1.0 as an option.
