### ISSUE TITLE
Add support for orjson.dump() and orjson.load() to read and write from and to files

### ISSUE THREAD

**Issue by StealthyExpertX** [ijl/orjson#329]
- Feature request.
**Add support for** ` orjson.dump()` and `orjson.load() ` **to read and write from and to file objects.**

I just feel this should be something the API has support for.

**Comment by setop** [comment]
completed ?

using v3.8.5, I still get `ImportError: cannot import name 'load' from 'orjson'`

**Comment by lenormf** [comment]
`v3.8.12` :(

```
AttributeError: module 'orjson' has no attribute 'load'
```
