### ISSUE TITLE
Cannot build orjson for raspberry pi 4

### ISSUE THREAD

**Issue by chulucninh09** [ijl/orjson#34]
When I tried to run `pip install orjson` in Ubuntu Server 18.04 for Raspberry Pi4, the following error occur:
```
Collecting orjson
  Using cached https://files.pythonhosted.org/packages/6c/d1/6357446e83e4774efcf9798ee17ec40ba573033f8b2f956bcadc2007a737/orjson-2.0.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-u6uu263e/orjson/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-u6uu263e/orjson/
```

There should be a wheel for manylinux stated in pypi, but instead I downloaded tar file and kinda install from source. What happened?

**Comment by ijl** [comment]
The manylinux1 wheel is for amd64 and ARM isnt supported. You would need to start by compiling https://github.com/PyO3/maturin for ARM, then run `maturin build --release`. I don\t know if it works.

**Comment by ourway** [comment]
This issue has not been solved. We can't use `orjson` for Arm32 and Raspberry environments.
