### ISSUE TITLE
Is there any possibility to add an option to accept integer greater than 64bits instead of throwing an exception?

### ISSUE THREAD

**Issue by XiaoHuiHui233** [ijl/orjson#340]
Is there any possibility to add an option to accept `int` greater than 64bits, convert it to `str` during serialization and it is still `int` after deserialization?

This requirement makes sense in certain situations, especially when using some tools of types such as `pydantic`. Since python supports integers with unlimited precision, it is easy to have such a type definition:
``` python
from pydantic import BaseModel


class DemoType(BaseModel):
    big_num: int


json_str = DemoType(a=1000000000000000000000000000000).json()
print(json_str)
print(DemoType.parse_raw(json_str))
```
In the case of using python's `json` standard library, we can get the following results:
```
{"a": 100000000000000000000000000000000000}
Test(a=100000000000000000000000000000000000)
```
This seems to be fine, although I'm not sure if it violates the JSON specification, but at least it performs correctly for the serialization task. Compared with the `json` standard library, I prefer to use `orjson` because it supports more types and is more efficient. But the next example is problematic:
``` python
from typing import Any

import orjson
from pydantic import BaseModel


def orjson_dumps(v: Any, *, default: Any):
    return orjson.dumps(v, default=default).decode()


class DemoType(BaseModel):
    big_num: int
    class Config:
        json_loads = orjson.loads
        json_dumps = orjson_dumps


json_str = DemoType(a=1000000000000000000000000000000).json()
```
In this example, I got `TypeError`.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 505, in pydantic.main.BaseModel.json
  File "<stdin>", line 2, in orjson_dumps
TypeError: Integer exceeds 64-bit range
```
It's true that the documentation of `orjson` clearly states that integers only support up to 64 bits. But in the data class like this, explicitly declaring the integer as `str` will make it more troublesome to use the integer later (need to force transform `str` to `int`, which is not elegant and inefficient). And the serialization work for the data class was interrupted by the exception. I wonder if there is an option or some kind of trick that can make `orjson` do its serialization work smartly. Such as allowing `int` to be automatically serialized as `str`, and converted to `int` when the strings are deserialized (the latter is actually Not much important because `pydantic` does it). In this way, there is no need to manually mark which ones need to be converted into `str` and which ones do not in the data structure mixed with small `int` and large `int`. This makes the code more elegant and efficient.

**Comment by noirbizarre** [comment]
This was closed as completed and I was watching this issue: has it been fixed/implemented ?

**Comment by XiaoHuiHui233** [comment]
@noirbizarre No, it doesn't. On the one hand, this issue is closed because it has not received a reply for a long time. On the other hand, it is because I am asking this question from the perspective of the user. In fact, from a development point of view, especially libraries like `orjson` use Rust as core logic. There are bound to be complex compatibility issues with infinite-precision ints. The best solution I can think of is to use Python code to process these integers, but this will have an efficiency bottleneck. So letting the user do their own preprocessing might be the best solution?
Combined with these realistic factors, I have given up the illusion that the author can provide an option to support these capabilities natively. Personally, I would define some new data structure to represent a number, which will automatically become a string when it exceeds a certain precision. At the same time, it is a custom type (not inherited from any basic type, such as int), which can be disposed of with `defaults`.
