### ISSUE TITLE
pip install not working 

### ISSUE THREAD

**Issue by XHIIHIIHX** [ijl/orjson#35]
my pip isn't completely borked afaik. I install ujson as example below. 

 uname -a
Linux daserver5 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

sudo -H pip --no-cache install orjson
Collecting orjson
  Downloading https://files.pythonhosted.org/packages/6c/d1/6357446e83e4774efcf9798ee17ec40ba573033f8b2f956bcadc2007a737/orjson-2.0.11.tar.gz (502kB)
     |################################| 512kB 2.8MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpnlz0SE
       cwd: /tmp/pip-install-5kd1BM/orjson
  Complete output (15 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 85, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
      obj = import_module(mod_path)
    File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
      __import__(name)
    File "/tmp/pip-build-env-zMe1jh/overlay/lib/python2.7/site-packages/maturin/__init__.py", line 31
      def get_config() -> Dict[str, str]:
                       ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpnlz0SE Check the logs for full command output.

..................................

sudo -H pip --no-cache install ujson
Collecting ujson
  Downloading https://files.pythonhosted.org/packages/16/c4/79f3409bc710559015464e5f49b9879430d8f87498ecdc335899732e5377/ujson-1.35.tar.gz (192kB)
     |################################| 194kB 2.6MB/s
Building wheels for collected packages: ujson
  Building wheel for ujson (setup.py) ... done
  Created wheel for ujson: filename=ujson-1.35-cp27-cp27mu-linux_x86_64.whl size=62574 sha256=df2b96489b43e481e81fb576c162d1513d4648e20e402cc122783a1fea12efa9
  Stored in directory: /tmp/pip-ephem-wheel-cache-kCTAly/wheels/28/77/e4/0311145b9c2e2f01470e744855131f9e34d6919687550f87d1
Successfully built ujson
Installing collected packages: ujson
Successfully installed ujson-1.35

**Comment by ijl** [comment]
This is because python2.7 is not supported. Try python3.5 or later. I'll specify a minimum version in packaging metadata to prevent pip from trying this.
