### ISSUE TITLE
orjson & macOS Ventura

### ISSUE THREAD

**Issue by danking** [ijl/orjson#387]
Hey there, I'm trying to track down why a user on macOS Ventura (13.4) is unable to install orjson from a wheel. The bottom of this issue links to their pip debug --verbose output.

I think my main confusion is that this version of pip does not report compatibility with any kind of macosx_11. Orjson, on the other hand, is publishing macosx_11 wheels (which would otherwise be compatible). Do you expect macOS Ventura to be compatible with macosx_11 wheels? The user has python 3.11 and pip 23.0.1, both of which are quite recent. Is it possible for orjson to publish their wheels as macosx_10_x instead?

Thanks for your time.

[pip debug --verbose](https://gist.github.com/danking/f93779b2f345b033e16ca3bf6f3e1986)

**Comment by danking** [comment]
They're using `pip install hail` which has a dependency on `orjson`. It seems like the true bug might be in what pip reports for macOS 13.4. I'll close for now.

If anyone else finds this issue and is looking for a quick fix, this should work (it will use a slightly older version of `orjson` which is compatible with your system):
```
pip install orjson --only-binary=:all:
```

**Comment by mirkolenz** [comment]
I also ran into this issue and solved it by pinning orjson to version `3.8.9`. Maybe you could consider reopening this issue as I think it is highly relevant and may be best addressed upstream.

**Comment by danking** [comment]
I don’t think the issue is with orjson or with Anaconda. There’s something wrong with what pip is reporting as compatible with Ventura. Unless Anaconda is manipulating pip in someway, it doesn’t seem like their fault.

**Comment by mirkolenz** [comment]
Hi @ijl, thanks for chiming in! I installed orjson via pip, so Anaconda is not involved. I am running the latest macOS (Ventura), so it may very well be the case that it is a bug with pip. Thanks for the clarification @danking
