### ISSUE TITLE
Poetry error while update package - Updating orjson (3.9.0 -> 3.9.1): Failed

### ISSUE THREAD

**Issue by jankrnavek** [ijl/orjson#394]
Poetry error while update package:
Os linux
Python 3.11.3

 • Updating orjson (3.9.0 -> 3.9.1): Failed

  RuntimeError

  Unable to find installation candidates for orjson (3.9.1)

  at env/lib/python3.11/site-packages/poetry/installation/chooser.py:76 in choose_for
       72│
       73│             links.append(link)
       74│
       75│         if not links:
    →  76│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       77│
       78│         # Get the best link
       79│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       80│

**Comment by iwoloschin** [comment]
I am also seeing this issue, but only on a "bare metal" (really a VM) Ubuntu 22.04.2 system. It seems to install fine in a python:3.11.3-slim docker container.

**Comment by iwoloschin** [comment]
Noticed the bot marked this as Stale, this is still a problem.
