### ISSUE TITLE
Relax strict enforcing of keys type to string

### ISSUE THREAD

**Issue by diefans** [ijl/orjson#40]
I would like to use orjson for structlog, but as it turns out, people are dumping arbitrary data for debugging purposes, where you cannot ensure dict key types are always strings.

So I ask, if there is even a technical reason to enforce string keys and if not, if it is possible to optionally relax this constraint...?

**Comment by ijl** [comment]
The keys need to be serialized as string. So how does the library know how an unknown type should be converted to str? json is probably calling str() on them? I could see an option to do that. Does it need to be more capable than that for your use?

**Comment by diefans** [comment]
I am thinking specifically on: 
``` python
>>> import json
>>> json.dumps({1: "foobar"})
'{"1": "foobar"}'
```
...so just calling `str(key)` I guess...

**Comment by diefans** [comment]
I don't know the internals of your excellent library, but I would go like this: 
``` python
try:
    # your usual call to dump the key
    return dump_to_json(key)
except KeyIsNotString:
    if not OPT_ENSURE_STRING_KEYS:
        raise JSONEncodeError("Dict key must be str")
    return dump_to_json(str(key))
```

**Comment by ijl** [comment]
Ok. Maybe there should be some handling of known types, or you have inconsistencies in output like `dumps({datetime.datetime.utcnow(): [...]})`, weird things like `dumps({(), []})`, and int/float keys can be faster than using libpython. It also allows the caller to create duplicate keys. That may be a problem for some implementations but as an option, sure. I think it's a reasonable option but I'm not sure of the details.

**Comment by diefans** [comment]
hmmm... If would have to decide, I would solely rely on the `__str__` implementation of the key. It is what one would expect I guess... Duplicates are the price you have to pay, but I think not that often in the context of a single dict.
At least for my case, keys are somehow homogeneous in terms of their type which will sanely reflect their uniqueness via str(), e.g. numbers or timestamps/datetimes.

Performance and logging belong somehow together, and if everything is well it just lowers the cost of operation, but in case of failure, I think everybody pays luckily the price for verbose logs - and as I can see performance would not be lowered for the well formed dicts.

**Comment by necaris** [comment]
Note that `structlog` as a specific library pretty much just calls `dumps` -- https://www.structlog.org/en/stable/_modules/structlog/processors.html#JSONRenderer

**Comment by diefans** [comment]
@necaris I don't see the point of your comment towards this specific issue.

**Comment by necaris** [comment]
@diefans just making sure everyone had the necessary context to know that structlog isn't doing anything special

**Comment by danieltahara** [comment]
Would be supportive of this. Running into the problem myself! Unfortunately makes serialize(deserialize) non-inverses of each other, which is perhaps undesirable.

**Comment by ijl** [comment]
It would be helpful to know the specific data that people want to serialize. The standard library's support is shown by this: `TypeError: keys must be str, int, float, bool or None`. It makes sense to me that that str, int, float, bool, UUID, and datetime would be serializable. 

How does this interact with `OPT_SORT_KEYS`? I suppose these sort, too, but that increases complexity.

**Comment by danieltahara** [comment]
> It would be helpful to know the specific data that people want to serialize. The standard library's support is shown by this: `TypeError: keys must be str, int, float, bool or None`. It makes sense to me that that str, int, float, bool, UUID, and datetime would be serializable.

My use case is timeseries data: integer unix milliseconds -> float value.
The stdlib handles it fine, so the suggestion of just opening it up to the full set of types the stdlib json supports makes sense.

**Comment by svrakitin** [comment]
@ijl Should we make an exception for `str, int, float, bool or None` as standard library does then? This way we can avoid calling `__str__`.

**Comment by diefans** [comment]
My use case is to log arbitrary stuff as json. Since logging should be fast and error resilient, orjson would be a fit... 

At the moment I traverse the structlog fields for dicts and convert all dict keys to strings to prevent an exception from happening while logging. Since the json serializer is already traversing all nested keys it would save this extra round trip... 

As I said above it would be totally fine if orjson could call `str(key)` on non-conforming keys so that the `__str__` implementation of that key would take over...

**Comment by ijl** [comment]
@svrakitin I think all supported non-container types like UUID included but yeah. It would be implemented natively, not calling `str()`, to me.

**Comment by ijl** [comment]
@diefans so you do that already with the standard library and it's not permissive enough?

**Comment by diefans** [comment]
@ijl I am sanitizing the json source before, which is basically a waste of cpu, since the serializer is in any way but limited doing the same.

**Comment by danieltahara** [comment]
What do you think the approach should be here @ijl ?

**Comment by ijl** [comment]
This is https://github.com/ijl/orjson#opt_non_str_keys in 2.5.0.

**Comment by hope-yao** [comment]
> This is https://github.com/ijl/orjson#opt_non_str_keys in 2.5.0.

I guess there is a slight side effect: when use <opt_non_str_keys> to serialize the dictionary, the key (say int type) will be automatically converted to string type. However, after deserialize, the key will not be converted back to the original type (say int).

**Comment by khanfarhan10** [comment]
Hmm, maybe we could keep some kind of metadata-based information on the original type of the key to be parsed, but then that would :

1. Be orjson library dependent.
2. Have an extra payload.
3. Would be non standard.

Can also be adding a user defined input on this, like an argument expected_key_format to reading the file (loads) and simply evaluate that with `literal_eval`
