### ISSUE TITLE
Naming python file 'json.py' causes segfaults

### ISSUE THREAD

**Issue by caffeinepills** [ijl/orjson#407]
I thought this was kind of amusing, and thought I would report it.

I had a test file I named simply: `json.py`, upon running code I kept getting no output. Further investigation through PyCharm had me receiving the segfault of `Process finished with exit code -1073741819 (0xC0000005)`

Narrowing down with:
```py
import orjson

raise Exception("Test")
```
Causes no exception to be printed and to segfault. Removing the exception still produces a segfault. Tested this with ujson and it doesn't seem to have this limitation. Only happens when the file is named `json.py`

Details:
Python 3.10 32 bit
Windows 10

**Comment by esentino** [comment]
I add something weard:
```py
import orjson
print(__name__)
```
generate output:
```
json
coredump
```
but when i comment out import orjson and run
output like
```
__main__
```
it's look like import orjson mess with `__name__`
