### ISSUE TITLE
Serialize UUID natively

### ISSUE THREAD

**Issue by Sytten** [ijl/orjson#41]
UUID are used a lot in APIs, it would be super great if they were supported natively. I know we can use the default, but it seems a bit slower (total time of the query) than if I already provide it a previously converted UUID to string.

**Comment by ijl** [comment]
It won't be appreciably faster because there's no C API for UUIDs. UUIDs are implemented as regular classes.

I see the argument for convenience but I think different callers may want to serialize in different ways? E.g., urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6.

**Comment by Sytten** [comment]
Good point, the difference I saw is most likely the small cost for the callback when working on very large payloads.

I think most people just want to do `str()` when using JSON, never seen anything else really.

**Comment by ijl** [comment]
Ok. For reference, (RFC 4122)[https://www.ietf.org/rfc/rfc4122.txt]. In Python, every version of a UUID is an instance of `uuid.UUID`, so there should be a check of `ob_type` for that (no subclasses). I don't think there's an API to get a u128 from Python (`self.int`), so you need to call `str()` on it?

**Comment by Sytten** [comment]
Usually we just call `str()`, but I am not sure if that is efficient enough for our use case (I would need to check the internal of `UUID`).

**Comment by necaris** [comment]
As far as I can tell, calling `str()` on the `UUID` converts `self.int` to hex and then inserts appropriate hyphens -- https://github.com/python/cpython/blob/0bcbfa43d55d9558cdcb256d8998366281322080/Lib/uuid.py#L277 

I'd be interested in taking a stab at a PR for this. I can't off the top of my head figure out how to get an instance of a `UUID` from Rust so I can get its `ob_type`, but I _think_ I see where I'd go once I had that.

**Comment by ijl** [comment]
To be released in 2.2.0.

**Comment by josh-stableprice** [comment]
Any chance of going the other way, having an option for loads enabling de-serialization of UUID values?

**Comment by necaris** [comment]
@josh-stableprice correct me if I'm wrong, but my understanding is that UUIDs can actually be represented in a number of ways -- so I would think we'd need some way (in JSON) to tell that something is intended to be a UUID rather than a hexadecimal string, or long integer?
