### ISSUE TITLE
mypy can't find OPT_SERIALIZE_DATACLASS

### ISSUE THREAD

**Issue by dbanty** [ijl/orjson#42]
For some reason mypy doesn't think that OPT_SERIALIZE_DATACLASS exists in the orjson module.  I really don't know why this is, it's clearly defined and in the .pyi file, so maybe it's an issue with mypy?  Figured I would post it here in case you know why.

My code:
```python
from dataclasses import dataclass
import orjson

@dataclass
class Test:
    value: str

test = Test("hi")
print(orjson.dumps(test, option=orjson.OPT_SERIALIZE_DATACLASS))
```

mypy's output is " error: Module has no attribute "OPT_SERIALIZE_DATACLASS"

**Comment by ijl** [comment]
mypy has a vendored version of the pyi in this project (via typeshed) and it hasn't been updated with the new options. It can be fixed by updating typeshed and waiting for that to be deployed or I think distributing a maturin mixed project with the pyi file. You can workaround with `# type: ignore`.

**Comment by dbanty** [comment]
Thanks @ijl I opened https://github.com/python/typeshed/pull/3532 to update typeshed.  

Doing a mixed project to include the stub files directly does seem like the better long term solution to prevent them getting out of sync.  I've never worked with maturin before but I'm happy to take a stab at it unless you already know how to do it.

**Comment by dbanty** [comment]
PR for typeshed has already been merged in, so I'm going to go ahead and close this issue which had a fairly specific scope.  Maybe including stub files directly can be a future improvement.

**Comment by ijl** [comment]
@dbanty thank you for fixing that in typeshed. I have some work already on a mixed project.
