### ISSUE TITLE
How to Force Use custom Encoders

### ISSUE THREAD

**Issue by nandish486** [ijl/orjson#425]
i saved datetime object in  json and saved by orjson.dumps(a, default=json_util.default), but it saves as string not $date : datestr

more over on reread by orjson.loads it reads datetime as str, how shall i do it like json module python 
![Screenshot (1840)](https://github.com/ijl/orjson/assets/93249676/93f02722-92f3-4598-a8bc-a77bdafe882a)

**Comment by unights** [comment]
Maybe you need to manually call `datetime.fromisoformat` to convert str into datetime object.

```python
from datetime import datetime

import orjson

a = {'now': datetime.now()}
# {'now': datetime.datetime(2023, 9, 5, 8, 32, 43, 288351)}

b = orjson.dumps(a)
# b'{"now":"2023-09-05T08:32:43.288351"}'

c = orjson.loads(b)
# {'now': '2023-09-05T08:32:43.288351'}

c['now'] = datetime.fromisoformat(c['now'])
# {'now': datetime.datetime(2023, 9, 5, 8, 32, 43, 288351)}

```

Any other Json parsers are the same.

```python
import json
from datetime import datetime

now = datetime.now()

# stdlib json cannot serialize datetime directly
s = json.dumps(json.dumps({'now': now.isoformat()}))
# '{"now": "2023-09-05T08:40:59.837139"}'

dic = json.loads(s)
dic['now'] = datetime.fromisoformat(dic['now'])
# {'now': datetime.datetime(2023, 9, 5, 8, 40, 59, 837139)}

print(type(dic['now']))
# <class 'datetime.datetime'>

```

If you want to deserialize Json directly into Python object, you may need to use [pydantic](https://docs.pydantic.dev/latest/).

```python
from datetime import datetime

from pydantic import BaseModel


class M(BaseModel):
    now: datetime


json_str = '{"now": "2023-09-05T08:40:59.837139"}'

m = M.model_validate_json(json_str)

print(repr(m))
# M(now=datetime.datetime(2023, 9, 5, 8, 40, 59, 837139))

print(repr(m.now))
# datetime.datetime(2023, 9, 5, 8, 40, 59, 837139)

print(type(m.now))
# <class 'datetime.datetime'>

```

**Comment by blthayer** [comment]
(Disclaimer: I am not the maintainer of `orjson`)

`orjson` is primarily for serialization. The deserialization into a Python dictionary (or list or other built-in primitive) is simple, as it should be. 

As @unights mentioned, you could use `pydantic`. Alternatively, I have had some success using [cattrs](https://github.com/python-attrs/cattrs) to do further conversions after `orjson` has taken my from bytes to a Python object.

**Comment by Fatal1ty** [comment]
As an alternative to pydantic and cattrs you may also use the mixin from [mashumaro](https://github.com/Fatal1ty/mashumaro#dataclassorjsonmixin):

```python
from dataclasses import dataclass
from datetime import datetime
from mashumaro.mixins.orjson import DataClassORJSONMixin

@dataclass
class M(DataClassORJSONMixin):
    now: datetime

json_str = '{"now": "2023-09-05T08:40:59.837139"}'

m = M.from_json(json_str)

print(repr(m))
# M(now=datetime.datetime(2023, 9, 5, 8, 40, 59, 837139))

assert m.to_json() == json_str
```

**Comment by nandish486** [comment]
> As an alternative to pydantic and cattrs you may also use the mixin from [mashumaro](https://github.com/Fatal1ty/mashumaro#dataclassorjsonmixin):
> 
> ```python
> from dataclasses import dataclass
> from datetime import datetime
> from mashumaro.mixins.orjson import DataClassORJSONMixin
> 
> @dataclass
> class M(DataClassORJSONMixin):
>     now: datetime
> 
> json_str = '{"now": "2023-09-05T08:40:59.837139"}'
> 
> m = M.from_json(json_str)
> 
> print(repr(m))
> # M(now=datetime.datetime(2023, 9, 5, 8, 40, 59, 837139))
> 
> assert m.to_json() == json_str
> ```

how to work with multiple data types just like json_utils from bson which is a pymongo library?

**Comment by Fatal1ty** [comment]
> how to work with multiple data types just like json_utils from bson which is a pymongo library?

If by multiple data types you mean third-party types, then there are [different ways](https://github.com/Fatal1ty/mashumaro#customization) to support them. Depending on the case in common you can register (de)serialization methods for those types per model / field / dialect, make those types serializable by inheriting `SerializableType` or use `SerializationStrategy` helper. Since you mentioned BSON, it's also easy to create your own mixin for that.

If this doesn't answer your question, I invite you to write more details in a new issue [here](https://github.com/Fatal1ty/mashumaro/issues/new/choose).

**Comment by nandish486** [comment]
> > how to work with multiple data types just like json_utils from bson which is a pymongo library?
> 
> If by multiple data types you mean third-party types, then there are [different ways](https://github.com/Fatal1ty/mashumaro#customization) to support them. Depending on the case in common you can register (de)serialization methods for those types per model / field / dialect, make those types serializable by inheriting `SerializableType` or use `SerializationStrategy` helper. Since you mentioned BSON, it's also easy to create your own mixin for that.
> 
> If this doesn't answer your question, I invite you to write more details in a new issue [here](https://github.com/Fatal1ty/mashumaro/issues/new/choose).

lemme tell your my scenerio,

i made my own db system which is RealmsDB,

it is a no sqli type system just as mongo db, 

it is too much fast, i am currently using std lib json in file,

but when i researched about other libraries like msgspec, ijson, orjson rapid json,
orjson was found to be "better" than std lib json in terms of reads and writes,

in json i use json.load(f, object_hook=json_util.object_hook) and similar for dumps

current read and write speeds are 0.02 and ~0.002 respectively.
from public reports i found orjson can be faster,
in my case i want to do similar with orjson for custom deserialisation , like OID, DATETIME, UUID etc which saves like $datatype in db.json, i am attaching photo for example. this helps in direct classes, no need of extra conversion until it is saved as str just as orjson does by default/

![image](https://github.com/ijl/orjson/assets/93249676/04e4266e-365f-40ea-bdd9-74d25dca888c)
