### ISSUE TITLE
Memory Allocation Issues

### ISSUE THREAD

**Issue by harshit2283** [ijl/orjson#429]
We're using orjson to read data through bytes, run an enricher and read that into dataframe

```
data = orjson.loads(data)
result = map(json_enricher, data)
result = list(result)
```

We're getting `JSONDecodeError: memory allocation failed: line 1 column 1 (char 0)` for a 500 MB compressed disk size file.
Our container size is 60GB and the max memory it goes to is 40GB, if I use a 120GB container then it works.

Is buffer memory set on RAM size, can I alter this?

Using orjson 3.9.1 with python 3.7.9

**Comment by alexey-cord-tech** [comment]
(just passing by looking for probably unrelated orjson memory issues, the below is in no way "official").

Well the most common strategy for growing buffers is "exponential with the factor between 1.5 and 2", which kind of matches your situation: the buffer grows to 40-ish Gb, is filled, the library wants to grow it to something between 60 and 80 GB; and it has to allocate the new buffer before copying and releasing the old one, so it needs 100-120Gb for the 'grow' operation. But the system only has 60 so the allocation fails. And it works if you increase available memory to 120Gb.

Kind of "as designed"...

**Comment by harshit2283** [comment]
Understood, thanks for the explanation :)
