### ISSUE TITLE
Support Default callable + native implementation

### ISSUE THREAD

**Issue by ZacharyThomas** [ijl/orjson#43]
Hi, 

I've been trying to figure out how to serialize an Enum in a data class. Currently I implemented a default which looks like:

```
def serialize_default(obj):
    if dataclasses.is_dataclass(obj):
        return dataclasses.asdict(obj)
    if isinstance(obj, Enum):
        return obj.value

result = orjson.dumps(response, default=serialize_default)
```

If possible, it'd be nice to be able to either have a native enum implementation, or be able to combine the native-options with my non-native default, for example:

```
def serialize_default(obj):
    if isinstance(obj, Enum):
        return obj.value

# I wish something like this worked
result = orjson.dumps(response, default=orjson.OPT_SERIALIZE_DATACLASS | serialize_default)  
```

Would this be do-able?

**Comment by ijl** [comment]
I think you might be looking for `orjson.dumps(obj, default=serialize_default, option=orjson.OPT_SERIALIZE_DATACLASS)`? That works fine.

**Comment by ZacharyThomas** [comment]
@ijl Thanks! Somehow the default vs option confused me.
