### ISSUE TITLE
add default hook to loads()

### ISSUE THREAD

**Issue by LBdN** [ijl/orjson#44]
Without a default hook in loads, the value of the default hook on dumps is small. 

The pattern of having classes with method from_json() and to_json() is really useful when combined with a default hook.

**Comment by ijl** [comment]
There are many python libraries that try to do something like this, e.g., marshmallow. I suggest using one of them.

**Comment by LBdN** [comment]
it's true but aren't they one or two order of magnitude slower ? speed is important in my case and the reason for my request.

**Comment by ijl** [comment]
Yes they're slow, and in terms of effort I think marshmallow is a six year project with over a hundred contributors. I'm not interested but of course the option is there to fork and implement this for yourself.
