### ISSUE TITLE
loads does not handle subclasses of str

### ISSUE THREAD

**Issue by emontnemery** [ijl/orjson#445]
Expected outcome:
Subclasses of str should be handled

Actual outcome:
`orjson.loads` blows up

Step by step reproduction:
```
>>> import orjson
>>> class MyStr(str):
...     pass
...
>>> obj = MyStr('"abc"')
>>> orjson.loads(obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
orjson.JSONDecodeError: Input must be bytes, bytearray, memoryview, or str: line 1 column 1 (char 0)
```

**Comment by FrnchFrgg** [comment]
Note that this also fails (even when trying to catch `MyStr` instances in a `default` handler):
```
>>> import orjson
>>> class MyStr(str):
...     pass
...
>>> obj = MyStr('key')
>>> orjson.dumps({obj: "value"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Dict key must be str
```

**Comment by emontnemery** [comment]
I don't agree these fall under "non str keys", that option is to allow keys which are `int`, `float` etc. In Python it's always assumed that if a class is handled, so are subclasses of it. Note that there's no way to write a type annotation in Python where a base class is allowed, but subclasses aren't.

**Comment by FrnchFrgg** [comment]
I found that you already merged #438 so I suppose you could just fallback to the same `str()` call for unknown `loads` inputs ?

**Comment by timkpaine** [comment]
@FrnchFrgg fyi that was closed as stale, not merged. Rebased in https://github.com/ijl/orjson/pull/454

**Comment by timkpaine** [comment]
Looks like the stale bot is very aggressive 😅, i’m going to incorporate this change in my fork [xorjson](https://github.com/timkpaine/xorjson)
