### ISSUE TITLE
Clarify the license ("AND" or "OR")

### ISSUE THREAD

**Issue by sschuberth** [ijl/orjson#448]
While https://github.com/ijl/orjson#license says "licensed under both the Apache 2 *and* MIT licenses" (emphasis mine), https://pypi.org/project/orjson/ says "Apache Software License, MIT License (Apache-2.0 *OR* MIT)" (again, emphasis mine). So, do users have a choice between `Apache-2.0 OR MIT`, or is it licensed under `Apache-2.0 AND MIT` at the same time? Also see https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/.

**Comment by ijl** [comment]
I intend that you can use it under either Apache 2 or MIT. I read the spec as being concerned with your choice.

> If required to simultaneously comply with two or more licenses, use the conjunctive binary "AND" operator to construct a new license expression

No.

> If presented with a choice between two or more licenses, use the disjunctive binary "OR" operator to construct a new license expression, where both the left and right operands are valid license expression values.

I think so?

**Comment by sschuberth** [comment]
> I intend that you can use it under either Apache 2 or MIT.

Then indeed you should use the SPDX expression `Apache-2.0 OR MIT` and change the text at

https://github.com/ijl/orjson/blame/399b36a0996d88a23aa88104e91c6a049e8e3ea1/README.md#L43 ("under both the Apache 2.0 and MIT licenses")

and

https://github.com/ijl/orjson/blame/399b36a0996d88a23aa88104e91c6a049e8e3ea1/README.md#L1217 ("under both the Apache 2 and MIT licenses")

to both say "under either the Apache-2.0 or the MIT license" (singular "license").

**Comment by ijl** [comment]
Perhaps you find what's on master now clearer.

**Comment by sschuberth** [comment]
> Perhaps you find what's on master now clearer.

Only partly, as the `README.md` still says "orjson is licensed under both the Apache 2.0 and MIT licenses". While I realize that "and" here is rather used colloquial, and not as the `AND` conjunction in the SPDX-expression-sense, it's still a bit misleading for people who are used to read SPDX expressions all day long 😉
