### ISSUE TITLE
About orjson.loads(obj, object_hook=) parameter option

### ISSUE THREAD

**Issue by TatanParker** [ijl/orjson#449]
Hi guys, does exist the idea of implementing **object_hook** option for json.loads()? Its quite useful when decoding objects to return them to it original format / state

**Comment by davidism** [comment]
This is answered "no" in the readme: https://github.com/ijl/orjson#will-it-deserialize-to-dataclasses-uuids-decimals-etc-or-support-object_hook, and you can find previous discussions by searching closed issues.
