### ISSUE TITLE
Could not install on Alpine Linux 3.11 and Rust 1.39.0

### ISSUE THREAD

**Issue by analytically** [ijl/orjson#46]
```
  error: could not compile `smallvec`.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --lib --release -- -C target-feature=+sse2 -C link-arg=-s`
  Running `maturin pep517 build-wheel -i python --manylinux=off --rustc-extra-args=-C target-feature=+sse2 --strip=on`
  Error: Command '['maturin', 'pep517', 'build-wheel', '-i', 'python', '--manylinux=off', '--rustc-extra-args=-C target-feature=+sse2', '--strip=on']' returned non-zero exit status 1.
```

**Comment by ijl** [comment]
There's some discussion in #8. If rustup works on Alpine now, someone could document this and specify how to run CI on Alpine.

**Comment by hartwork** [comment]
#8 has been closed now and installing orjson on Alpine Linux 3.11 and Rust 1.39.0 still does not work. Maybe with things like https://github.com/ijl/orjson/issues/8#issuecomment-570335365 . I would vote for re-opening and maybe pinning this ticket.

**Comment by ijl** [comment]
Using https://pkgs.alpinelinux.org/package/v3.11/community/x86_64/rust? That's stable, and this requires nightly. If you can document how to install it, great.

**Comment by hartwork** [comment]
> Using https://pkgs.alpinelinux.org/package/v3.11/community/x86_64/rust? That's stable, and this requires nightly.

Yes and yes.

> If you can document how to install it, great.

I stopped research half way due to timeout, so I cannot, at least yet.

So we cannot re-open and/or pin this ticket for the next person to maybe find this quicker?

**Comment by hartwork** [comment]
> > If you can document how to install it, great.
> 
> I stopped research half way due to timeout, so I cannot, at least yet.

Based on https://github.com/ijl/orjson/issues/8#issuecomment-570335365 by @scuml I can confirm that this Dockerfile works for orjson on Alpine 3.11:

```Dockerfile
FROM python:3.8-alpine

RUN apk update \
        && \
    apk add build-base wget

RUN wget -Oinit.sh https://sh.rustup.rs \
        && \
    sh init.sh -y \
        && \
    rm init.sh

ENV PATH="/root/.cargo/bin:${PATH}"

RUN rustup install nightly \
        && \
    rustup default nightly

ENV RUSTFLAGS="-C target-feature=-crt-static"

RUN pip install --no-binary=orjson orjson==2.5.1

RUN python -c 'import orjson; print(orjson.loads("[1, true]"))'
```
It took about 10 minutes total runtime over here.

**Comment by gatopeich** [comment]
The recipe above only works now with **nightly-2020-09-14**
Tested on python:3.8-alpine3.12 and orjson==3.3.1
```
FROM python:3.8-alpine3.12
RUN apk add build-base wget
ENV PATH="/root/.cargo/bin:${PATH}"
ENV RUSTFLAGS="-C target-feature=-crt-static"
RUN wget https://sh.rustup.rs -O rustup-init \
    && sh rustup-init -y --default-toolchain nightly-2020-09-14
RUN pip install --no-binary=orjson $(grep -o 'orjson[^#]*' runtime.deps)
RUN python -c 'import orjson; print(orjson.loads("[1, true]"))'
```

I am now testing on plain Alpine3.12, where binary manylinux build seems a bit slower...
