### ISSUE TITLE
orjson 3.10 doesn't include macOS wheels for CPython 3.8, 3.9, 3.10

### ISSUE THREAD

**Issue by timoffex** [ijl/orjson#468]
Previous version: https://pypi.org/project/orjson/3.9.15/#files

* orjson-3.9.15-cp38-cp38-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl 
* orjson-3.9.15-cp39-cp39-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl 
* orjson-3.9.15-cp310-cp310-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl 
* orjson-3.9.15-cp311-cp311-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl 
* orjson-3.9.15-cp312-cp312-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl 

New version: https://pypi.org/project/orjson/3.10.0/#files

* orjson-3.10.0-cp311-cp311-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl 
* orjson-3.10.0-cp312-cp312-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl 

This broke our CI, which `pip install`s `orjson` but don't have `cargo`.

One workaround is to install `cargo` in the CI, but it feels wrong because we don't otherwise use Rust. Another workaround is to pin the version for now, but whether that's right depends on whether this was an intentional change.

Are those wheels intentionally dropped from the new and future versions?

**Comment by ijl** [comment]
Thanks, Azure DevOps was sensitive to whether the tag was pushed before or after cloning on the commit's CI ru as it doesn't do a separate CI run on the tag. Five wheels uploaded a few minutes ago.
