### ISSUE TITLE
the dump function may not work properly with version 3.8.6.

### ISSUE THREAD

**Issue by TakayoshiBBQ** [ijl/orjson#471]
I use the dump function, but there are cases in which the output does not come out in JSON format.
This issue occurs with version 3.8.6. (It doesn't occur with version 3.8.7)

It seems likely that this issue occurs when dealing with a specific number of characters. For example 1024, 4096.
And, the character ']' is not outputted.NULL is outputted. 
Due to the lack of the character ']', it is not in JSON file format.

Could you tell me why this issue occur ? 
(Please tell me about applicable parts of source code)

I have attached an example of this issue.
[test_json.txt](https://github.com/ijl/orjson/files/14929927/test_json.txt)

Please convert file type to python(.py).

**Comment by ijl** [comment]
Thank you for reporting it. I can't reproduce on 3.8.6. 3.8.7 and later have had fixes, so I think your issue is resolved.
