### ISSUE TITLE
Crash reported with 3.10.2+ on aarch64

### ISSUE THREAD

**Issue by bdraco** [ijl/orjson#495]
https://github.com/home-assistant/core/issues/118507#issuecomment-2151033933

```
Thread 1 "hass" received signal SIGBUS, Bus error.
0xf5f6f9f6 in <orjson::serialize::per_type::unicode::StrSerializer as serde::ser::Serialize>::serialize ()
   from target:/usr/local/lib/python3.12/site-packages/orjson/orjson.cpython-312-arm-linux-musleabihf.so
```

**Comment by bdraco** [comment]
Maybe related https://github.com/ijl/orjson/commit/d81712f222c768d4313a0d83be04e37c42ce7177

**Comment by bdraco** [comment]
I thought it was armv7 as well but the linked issue is aarch64 as well

**Comment by bdraco** [comment]
I asked for explicit verification in both of the linked issues and it's now confirmed both issues are on aarch64

**Comment by ijl** [comment]
Is your provided setup musl libc and 3.12? `orjson-3.10.3-cp312-cp312-musllinux_1_2_aarch64.whl` was installed?

**Comment by bdraco** [comment]
Yes 

Musl (alpine 3.19), cpython 3.12, Installed from wheel

**Comment by ijl** [comment]
[3.10.6](https://github.com/ijl/orjson/releases/tag/3.10.6) has arm7 wheels and should be appropriate to try. It possibly was an issue with the u64 aliased write.

**Comment by bdraco** [comment]
Thanks for the heads up. I’ll give it a shot when I get home later tonight

**Comment by bdraco** [comment]
Initial testing looks good.

Will have a better idea if everything is OK in early August when HA core 2024.8.x ships

**Comment by bdraco** [comment]
So far so good with the HA beta. Will followup again after the stable release.

Thanks

**Comment by bdraco** [comment]
Home Assistant stable release shipped yesterday and everything seems to be ok. Thanks for the fix!

**Comment by ijl** [comment]
Thanks for letting me know.
