### ISSUE TITLE
Publish a new version with `default` support?

### ISSUE THREAD

**Issue by phyng** [ijl/orjson#5]
I build and test the code from master(https://github.com/ijl/orjson/commit/15757e064586d5c6cf60528cea6ada13bf302b15) on macOS, It works fine, but I want to deploy it to Ubuntu server.

**Comment by ijl** [comment]
Yes, within a few days.

**Comment by phyng** [comment]
@iji Thanks! I build and deploy it to Ubuntu, looks like works well.

**Comment by ijl** [comment]
This is available in the 2.0.0 release on PyPI.
