### ISSUE TITLE
Memory leak issue closed with no comment?

### ISSUE THREAD

**Issue by Klavionik** [ijl/orjson#504]
I noticed that this issue #483 was recently closed without any comment. It was mark as "completed", but there's no related PR and I can still reproduce the issue using the latest commit in the repository and [this](https://github.com/ijl/orjson/issues/483#issuecomment-2179763756) example code.

@ijl May I ask you to provide a short explanation? I mean, the issue seems real and reproducible, why closing it?

**Comment by Klavionik** [comment]
This is one aggressive bot, I must say. :)

**Comment by JWCook** [comment]
I am also curious about this. The report in #483 appears to be valid, and I don't think that warranted closing and locking it without explanation.

That and the rather _accelerated_ [stalebot schedule](https://github.com/ijl/orjson/blob/master/.github/workflows/stale.yaml) indicate to me that the maintainer is overburdened right now, which I can certainly empathize with. Puts users in an awkward spot, though.
