### ISSUE TITLE
Standard library compatibility and monkey patching

### ISSUE THREAD

**Issue by rpatterson** [ijl/orjson#514]
I need to use `orjson` in multiple external packages that use `json` from the standard library. I'll write compatibility wrappers and functions to monkey patch the standard library such that `orjson` is used under the hood in those external packages. I can package that under a new, separate distribution, but I'd be happy to submit it as a PR to this package instead. Is there any interest from the maintainers in merging such a PR that passes their review?

**Comment by ijl** [comment]
I suggest publishing a small library in the same way [orjsonl](https://github.com/umarbutler/orjsonl) did for line-delimited JSON.
