### ISSUE TITLE
Document default examples and edge cases

### ISSUE THREAD

**Issue by aovasylenko** [ijl/orjson#52]
Hi guys, there is an issue:

Documentation says:
_"If no object is returned by the default callable but also no exception was raised, it falls through to raising JSONEncodeError on an unsupported type."_

So I expect to see JSONEncodeError in this case
`orjson.dumps(Decimal(1), default=lambda *a, **kwargs: None)`
but I'm getting b'null'

Version: 2.2.0

Thanks in advance!

**Comment by ijl** [comment]
The lambda is returning the body, so:

```python
orjson.dumps(Decimal(1), default=lambda *a, **kwargs: {})
b'{}'
>>> json.dumps(Decimal(1), default=lambda *a, **kwargs: True)
'true'
```

Possibly a static analyzer such as Pylint could warn about this, I don't know.

**Comment by aovasylenko** [comment]
Should
```
def default(obj):
  return None
```
always raise an error on custom objects?

**Comment by ijl** [comment]
The implementation at the C API layer is that there are two separate objects; `Py_None()`, which is a valid object that is serialized as null, and a null pointer (no return value). I think maybe the default `None` return when calling a function in Python is imputed by the interpreter, because it doesn't happen in a C API call.

**Comment by aovasylenko** [comment]
Maybe solution could be in mentioning in the documentation raising JSONEncodeError explicitly

**Comment by ijl** [comment]
Yes, https://github.com/ijl/orjson#default could have examples.

**Comment by ijl** [comment]
The docs were inaccurate, and for the above situation, you need to explicitly raise an error. See https://github.com/ijl/orjson#default now.

**Comment by aovasylenko** [comment]
Thank you @ijl
