### ISSUE TITLE
Import zoneinfo crashes when hasattr(sys, 'abiflags') is false

### ISSUE THREAD

**Issue by Antares0982** [ijl/orjson#522]
When orjson running on embedded python on some platforms (Android, IOS), the "abiflags" may not be defined (ABIFLAGS macro is not defined when compiling CPython). The `module` in code below is nullptr and causes crash.
```rust
let module = PyImport_ImportModule("zoneinfo\0".as_ptr() as *const c_char);
let module_dict = PyObject_GenericGetDict(module, null_mut());
```

**Comment by Antares0982** [comment]
importing zoneinfo._tzpath will result in a call to sysconfig._get_sysconfigdata_name(), which raises an AttributeError, and causes failing to import zoneinfo.

**Comment by ijl** [comment]
I don't know anything about embedded Python on Android/iOS and how a shared library would even work without ABIFLAGs. It's definitely not supported. If you have a trivial patch I could merge it but assume it would break without CI.

**Comment by Antares0982** [comment]
If someone has the same problem, change these lines to
```rust
    let module = PyImport_ImportModule("zoneinfo\0".as_ptr() as *const c_char);
    if module.is_null() {
        PyErr_Clear();
        return null_mut();
    }
    let module_dict = PyObject_GenericGetDict(module, null_mut());
```
As long as zoneinfo cannot be imported, there is no python object that has type `zoneinfo.Zoneinfo` so this should be safe
