### ISSUE TITLE
Relaxed JSON deserializing

### ISSUE THREAD

**Issue by stefanodvx** [ijl/orjson#528]
Is there any way to deserialize a relaxed JSON structure using orjson? Relaxed JSON is something like that `{key: "value"}`. The difference is that keys are not quoted.

```
>>> orjson.loads('{key: "value"}')
Traceback (most recent call last):
  ...
orjson.JSONDecodeError: unexpected character: line 1 column 2 (char 1)
```

**Comment by ijl** [comment]
This supports RFC 8259.
