### ISSUE TITLE
Support 65+ bit integers

### ISSUE THREAD

**Issue by autumnjolitz** [ijl/orjson#53]
Hi,

We have some ML projects that have been known to generate 67 bit integers. `orjson` can't deserialize them (thankfully, unlike `ujson` it actually throws an exception, so I can failsafe to `json`)

```
>>> import orjson
>>> orjson.dumps({'key': int('1'*67, 2)})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
orjson.JSONEncodeError: Integer exceeds 64-bit range
>>> value = horcrux._json.dumps({'key': int('1'*67, 2)})
Unable to fastdump JSON, failsafe to stdlib json! [Slow!!]
Traceback (most recent call last):
  File "/Users/autumn/software/horcrux/horcrux/__init__.py", line 36, in fast_dumps
    value: bytes = self.fastjson.dumps(item)
orjson.JSONEncodeError: Integer exceeds 64-bit range
>>> value
'{"key": 147573952589676412927}'
>>> orjson.loads('{"key": 147573952589676412927}')
{'key': 1.4757395258967641e+20}
>>> orjson.dumps(_)
b'{"key":1.4757395258967641e20}'
>>> 147573952589676412927 - 1.4757395258967641e20
0.0
```

One quick fix suggestion would be to simply cast items larger than int64 to floats as the following works just fine:

```
>>> orjson.loads('{"key": 1.4757395258967641e20}')
{'key': 1.4757395258967641e+20}
```

A better one would be to return `int` for `int`. Thankfully, I can failsafe to stdlib json to handle the bignums when they come in. 😃

**Comment by ijl** [comment]
I think 128 bit integers are so far from the spec and what is supported in other implementations that it would not be worth supporting.

**Comment by autumnjolitz** [comment]
I don't feel that's the right answer - the fact that `.dumps` deviates from standard library JSON and throws an error (as opposed to writing `1.4757395258967641e20`) is still there. 

I can understand not wanting to support 128 bit ints (even though the spec only requires that it be a Number type) - what I don't understand is why `orjson` does not return `1.4757395258967641e20` - shouldn't it be able to emit the same output for the same supported input? 😐

**Comment by MrMrRobat** [comment]
That's actually looks so unobvious for me:

```py
import json
>>> json.dumps({'key': int('1'*67, 2)})
'{"key": 147573952589676412927}'
json.loads(value)
{'key': 147573952589676412927}
orjson.loads(value)
{'key': 1.4757395258967641e+20}
```
