### ISSUE TITLE
Feature request: Streams (Willing to submit PR)

### ISSUE THREAD

**Issue by ayjayt** [ijl/orjson#534]
Hi, are you willing to look at a PR that proposes an alternative deserialize function that will return, from a "chunk" (whatever is the given datastructure, I suppose), a single decoded object and the a pointer to the rest of the chunk?

```python
input = b"{}{}"
object, rest = deserialize_stream(input) # dict(), b"{}"


input = b"{'key':"
object, rest = deserialize_stream(input) # None, b"{'key':"
```

**Comment by ijl** [comment]
I suggest developing this in your own fork. It would likely be too much of a change to merge back, but in any case that would be clear when there's a mature implementation.
