### ISSUE TITLE
Feature request: Support parsing multiple documents in a single call 

### ISSUE THREAD

**Issue by akx** [ijl/orjson#536]
[Looks like](https://github.com/ibireme/yyjson/blob/master/doc/API.md) `yyjson` supports `YYJSON_READ_STOP_WHEN_DONE`, which would allow reading multiple documents from a single buffer. ([Based on this answer](https://stackoverflow.com/a/55797976/51685) `serde_json` should too.)

This would practically then support NDJSON/JSONL (#428 touched upon this in the past).

Ideally, this new "`loads_multiple`" API would return a lazy `Iterator[Any]`:

```python
for doc in orjson.loads_multiple('{"foo":"bar"}\n{"baz":"quux"}\n{"spam": "eggs"}'):
    if "baz" in doc:  # leaves `"spam":"eggs"` unparsed
        break
```

**Comment by ijl** [comment]
Do you want something like [orjsonl](https://github.com/umarbutler/orjsonl)? Someone will at some point want to decompress, as that supports, or split up a document and process it in parallel, or whatever. So best handled a layer above. This library just does document to Python and vice versa.

**Comment by akx** [comment]
Not exactly. All `orjsonl` does is call `orjson.loads` repeatedly, which is what I can do without an extra library 😄 

What `orjsonl` (or any other JSONL library) _can't_ do is parse `{"foo":"bar"}{"baz":"quux"}` into two objects, which should be possible with `YYJSON_READ_STOP_WHEN_DONE` - but parsing JSONL/NDJSON would be a nice side effect.

**Comment by ivanychev** [comment]
Thanks for an amazing library. I second this! A lot of use cases of interaction between backend and data science is exchanging JSONL files so parsing them natively with a single call without calling `orson.loads` in a loop would be a nice feature and shouldn't be hard to implement.
