### ISSUE TITLE
Support for Subclasses of builtins, Enums

### ISSUE THREAD

**Issue by seandstewart** [ijl/orjson#61]
Hello - 

I'm very interested in making use of this library for its native support of dataclasses, however I have a few minor blockers:

1. I make use of `enum.Enum` subclasses quite extensively,
2. I also make use of subclasses of builtins for data-validation.

Both of these cases are natively handled by the builtin json library and other third-party software (rapidjson, ujson, etc). I think perhaps supporting subclasses of builtins would solve both of my two blockers.

I also understand that I could implement a `default` callable for these cases. However, in a code-base using almost-exclusively subtypes in this manner, the potential performance gains are lost by constantly bailing out to the default. 

Unfortunately, I'm not familiar enough with Rust or its Python interface to suggest an implementation, but I can provide a test case:

```python
import enum
import dataclasses

import orjson

class ShortStr(str):
 
    def __new__(cls, *args, **kwargs):
         v = str.__new__(cls, *args, **kwargs)
         assert len(v) < 10, "Values must be less than 10 chars!"
         return v


class Choice(int, enum.Enum):
    YES = 1
    NO = 0
    MAYBE = -1


@dataclasses.dataclass
class UncertaintyPrinciple:
    subject: ShortStr
    decision: Choice

    def json(self) -> str:
        return orjson.dumps(self, option=orjson.OPT_SERIALIZE_DATACLASS)

```

**Comment by ijl** [comment]
Subclasses aren't serialized because there's no obviously correct way to serialize every subclass someone creates. I don't mind accepting a patch supporting enums if there is one correct way to serialize all enums and it can handle all weird variations (e.g., you can make enums of dictionaries).

Take the above and add:

```python
import string
import random 
import json
import rapidjson

data = [
    UncertaintyPrinciple(
        ShortStr("".join(random.choice(string.ascii_lowercase) for _ in range(0, 9))), 
        Choice(random.choice((-1, 0, 1)))
    ) for _ in range(10000)
]

data_as_primitives = [
    {
        "subject": "".join(random.choice(string.ascii_lowercase) for _ in range(0, 9)),
        "decision": random.choice((-1, 0, 1)),
    } for _ in range(10000)
]

def default(obj, /):
    cls = obj.__class__
    if cls == ShortStr:
        return str(obj)
    elif cls == Choice:
        return int(obj)
    elif cls == UncertaintyPrinciple:
        return dataclasses.asdict(obj)
    raise TypeError
```

I see:

```python
In [2]: %timeit json.dumps(data, default=default)
148 ms ± 6.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [3]: %timeit rapidjson.dumps(data, default=default)
126 ms ± 5.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [4]: %timeit orjson.dumps(data, option=orjson.OPT_SERIALIZE_DATACLASS, default=default)
4.94 ms ± 296 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [5]: %timeit orjson.dumps(data_as_primitives, option=orjson.OPT_SERIALIZE_DATACLASS, default=default)
1.2 ms ± 116 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

It's slower to go through `default` of course but the intuition that `default` is slow enough to cause a 30x slowdown and negate any benefit isn't right.

Implementing support for enums or having `default` use `_PyObject_Vectorcall` (requiring conditional compilation based on python version in order to still support 3.6) are possible optimizations.

**Comment by seandstewart** [comment]
A simple method for extracting the "real" value of an Enum is just accessing `Enum.value`. That should suffice for a simple, default handling of Enums. As for subclasses, I suppose I see your point there - subclasses may violate standard representations and you have no way to know that.

**Comment by navidnabavi** [comment]
i faced with this problem in django-rest-framework library. because the result of django rest framework views return their result with subtype of list called ReturnList. So it is not easily possible to use it in many cases.

**Comment by ijl** [comment]
Support for enums is on master.

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/2.6.3

**Comment by navidnabavi** [comment]
Does it fix other subclasses like `dict`?

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/3.0.0

**Comment by seandstewart** [comment]
This is huge! Thanks @ijl!

**Comment by navidnabavi** [comment]
GREAT!
