### ISSUE TITLE
json.dumps(float('inf')) should throw a ValueError

### ISSUE THREAD

**Issue by LegNeato** [ijl/orjson#62]
The default `json`throws a `ValueError` here when `orjson` does not:

``` python
       with self.assertRaises(ValueError):
            json.dumps(float('inf'))
```

**Comment by ijl** [comment]
```python
>>> json.dumps(float("inf"))
'Infinity'
```

**Comment by sasha00123** [comment]
@ijl Why did you close the issue? json dumps it as 'Infinity', while orjson as 'null' - not the most obvious behavior... Or is it just hard to implement?
