### ISSUE TITLE
Add support for `collections.OrderedDict`

### ISSUE THREAD

**Issue by LegNeato** [ijl/orjson#63]
`collections.OrderedDict` does not seem to work with `orjson`. Is there any way I can tell `orjson` to  treat it like a dict?

**Comment by LegNeato** [comment]
Actually, the more general way to fix this might to to support `Mapping`: https://docs.python.org/3/glossary.html#term-mapping

**Comment by ijl** [comment]
This is discussed in detail in the documentation.

**Comment by LegNeato** [comment]
Sorry, I am already using `default` but it is ugly / slow with nested `OrderedDicts`. As `OrderedDict` is pretty well defined, would you take a patch to push this down into the rust layer?
