### ISSUE TITLE
[Question] - How to properly include this locally for a project?

### ISSUE THREAD

**Issue by TheSecEng** [ijl/orjson#64]
Is it possible to include this in a project locally, so that users don't need to install the package themselves?

Having it in a local folder like this doesn't seem to work.

```
Project
    - lib
        - orjson
            - orjson.so
```

```python
from ./lib import orjson
```

**Comment by ijl** [comment]
I don't think that's possible. Please have it installed using a package manager like pip.

**Comment by TheSecEng** [comment]
@ijl Thanks, just wanted to make sure.
