### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by ijl** [ijl/orjson#65]
Version 3 will serialize dataclass, UUID, numpy, and probably enum objects by default. The options for these will remain but be 0.

**Comment by fengsi** [comment]
Is it async?

**Comment by stalkerg** [comment]
what about deserialize for datetime or UUID? It's a very important feature I suppose.

**Comment by ijl** [comment]
It can't deserialize str to datetime or UUID, float to decimal, etc., without knowing the intended type.

The functions hold the GIL.

**Comment by stalkerg** [comment]
How does it work in RapidJSON? It's really important. Maybe we can use regexp to determine it? As an optional feature of course.

**Comment by ijl** [comment]
Deserializing str that look like datetime to datetime isn't usable. The caller can't assume they have a datetime from a str with no parse errors or assume a str when user input could well be a str containing only a datetime. This requires the caller to specify what type they expect, how missing values should be handled, etc--it becomes a validation library, of which there are many, and the issue trackers on those suggest they are working against the limitations of Python and conflicting, idiosyncratic business requirements.

**Comment by ijl** [comment]
#78 suggests numpy not be serialized by default.

**Comment by stalkerg** [comment]
Does it mean you suppose the RapidJSON approach is wrong? 

>it becomes a validation library

I disagree with it if you verify str for a date inside it does not mean you started to validate it. 
It's a very common feature for many JSON libs, also you can rely on
https://tools.ietf.org/html/rfc7493#section-4.3

> The caller can't assume they have a datetime from a str with no parse errors or assume a str when user input could well be a str containing only a datetime. 

it's fine if I can trust a source of JSON.

**Comment by ijl** [comment]
@stalkerg sorry I disagree, maybe rapidjson is more appropriate for your use case.

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/3.0.0
