### ISSUE TITLE
Serialize to str

### ISSUE THREAD

**Issue by 3ddi** [ijl/orjson#66]
Assuming many would want to replace current json libraries with this one, str will be the expected output. You can always use a wrapper with decode, but then there is a performance impact.

I was mainly wondering why this feature isn't part of the library as I'm willing to help add it.

**Comment by ijl** [comment]
`bytes` is the correct type for a serialized blob. That alone is good reason but the performance is better for the case worth supporting for the future, something like an API renderer that writes to bytes, or a user who writes an internal library function to serialize, as well.

**Comment by tribals** [comment]
> `bytes` is the correct type for serialized blob.

Except for JSON, is it is text-based by definition:

> JavaScript Object Notation (JSON) is a lightweight, text-based, language-independent data interchange format. [^1]

[1]: https://tools.ietf.org/html/rfc7159

**Comment by danieldjewell** [comment]
To expand on @tribals: here's the latest RFC... https://tools.ietf.org/html/rfc8259

**Comment by CaselIT** [comment]
> 
> 
> `bytes` is the correct type for a serialized blob. That alone is good reason but the performance is better for the case worth supporting for the future, something like an API renderer that writes to bytes, or a user who writes an internal library function to serialize, as well.

It would be useful to have as an option, since many places expect the output of dumps to be a `str`. I think it would make replacing the builtin library easier.

Currently I'm doing this when I need the output as string, but it adds a function call that could be avoided with an option included in orjson
```py
def dumps_str(data):
  return orjson.dumps(data).decode()
```

**Comment by jrobbins-LiveData** [comment]
Without arguing with the premise, namely 

> `bytes` is the correct type for a serialized blob

**Comment by stalkerg** [comment]
Nowadays, standard `loads` support `bytes` the problem is in `dumps` only.
