### ISSUE TITLE
Get a error when I build the project on macos

### ISSUE THREAD

**Issue by yufeiok1983** [ijl/orjson#68]
➜  orjson git:(master) ✗ maturin build --no-sdist --release --strip --manylinux off
🔗 Found pyo3 bindings
🐍 Found CPython 3.7m at python3.7
   Compiling proc-macro2 v1.0.9
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.17
   Compiling cfg-if v0.1.10
   Compiling libc v0.2.68
   Compiling ryu v1.0.3
   Compiling serde v1.0.105
   Compiling memchr v2.3.3
   Compiling typenum v1.11.2
   Compiling proc-macro-hack v0.5.14
   Compiling getrandom v0.1.14
   Compiling lazy_static v1.4.0
   Compiling regex-syntax v0.6.17
   Compiling bitflags v1.2.1
   Compiling byteorder v1.3.4
   Compiling itoa v0.4.5
   Compiling autocfg v1.0.0
   Compiling version_check v0.9.1
   Compiling unindent v0.1.5
   Compiling lexical-core v0.7.4
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.2.0
error[E0554]: `#![feature]` may not be used on the stable release channel8/100: smallvec, scopeguard, regex-syntax, version_check
  --> /Users/yufei/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:29:32
   |
29 | #![cfg_attr(feature = "union", feature(untagged_unions))]
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/yufei/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.2.0/lib.rs:30:41
   |
30 | #![cfg_attr(feature = "specialization", feature(specialization))]
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^

   Compiling packed_simd v0.3.3
error: aborting due to 2 previous errors                              ] 19/100: smallvec, regex-syntax, packed_simd(build.rs), version_check

For more information about this error, try `rustc --explain E0554`.   ] 19/100: smallvec, regex-syntax, packed_simd(build.rs), version_check

error: could not compile `smallvec`.
warning: build failed, waiting for other jobs to finish...
error: build failed
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --lib --release -- -C link-arg=-undefined -C link-arg=dynamic_lookup -C link-arg=-s`
➜  orjson git:(master) ✗

**Comment by ijl** [comment]
Please see the README. It requires nightly.
