### ISSUE TITLE
Ignore null serialize

### ISSUE THREAD

**Issue by ihatiko** [ijl/orjson#69]
Hello, i tried serialize dataclass, how to ignore null ?

`@dataclass
class CDCObject:
    schema_ver: str

def default(obj):
    print(type(obj))
    if isinstance(obj, int):
        print(123)
        return str(obj)
    raise TypeError

obj = CDCObject(None)
result = orjson.dumps(obj, default=default, option=orjson.OPT_SERIALIZE_DATACLASS)

print(result)`

and my default function does not invoked (

**Comment by ijl** [comment]
default is only called if the object isn't supported, but with that opt specified, it is.
