### ISSUE TITLE
[feature request] Add json-tricks serialization option

### ISSUE THREAD

**Issue by kivo360** [ijl/orjson#71]
I was looking at the `json-tricks` library and loved the complex serialization that they have. I love the speed of orjson just as much. I was wondering. How do I add custom serialization to orjson?

I'd like to add their declared datetime and numpy serialization to the library with orjson's speed.

**Comment by ijl** [comment]
Could you show examples?

**Comment by kivo360** [comment]
For `json_tricks` one of the more useful aspects to the library is that it declares all of the types within a numpy array. That's so, when one were to deserialize the json that's produced, the library can appropriately cast the types back into what they're meant to be. In essence, a schema is added in. 

For example. The following code creates a small numpy array then dumps it using json-tricks:
```py
import numpy as np
arr = np.arange(0, 10, 1, dtype=uint8).reshape((2, 5))
print(dumps({'mydata': arr}))
```

The resulting code is the following:
```py
{
        "mydata": {
                "dtype": "uint8",
                "shape": [2, 5],
                "Corder": true,
                "__ndarray__": [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
        }
}
```

Notice it doesn't just leave the numpy array as a set of primatives, it also adds information explaining how to manage the primitives. This is amazing for many reasons. The primary thing I can see this being used for creating a consistent feature store or sending complex data types through an API without needing to use pickle.

**Comment by kivo360** [comment]
Having looked at the code [here](https://json-tricks.readthedocs.io/en/latest/_modules/json_tricks/encoders.html#numpy_encode) one can see the type of pre-processing that's done to properly serialize numpy arrays.

**Numpy Encoding:**

```py
def numpy_encode(obj, primitives=False):
	"""
	Encodes numpy `ndarray`s as lists with meta data.
	
	Encodes numpy scalar types as Python equivalents. Special encoding is not possible,
	because int64 (in py2) and float64 (in py2 and py3) are subclasses of primitives,
	which never reach the encoder.
	
	:param primitives: If True, arrays are serialized as (nested) lists without meta info.
	"""
	from numpy import ndarray, generic
	if isinstance(obj, ndarray):
		if primitives:
			return obj.tolist()
		else:
			dct = hashodict((
				('__ndarray__', obj.tolist()),
				('dtype', str(obj.dtype)),
				('shape', obj.shape),
			))
			if len(obj.shape) > 1:
				dct['Corder'] = obj.flags['C_CONTIGUOUS']
			return dct
	elif isinstance(obj, generic):
		if NumpyEncoder.SHOW_SCALAR_WARNING:
			NumpyEncoder.SHOW_SCALAR_WARNING = False
			warning('json-tricks: numpy scalar serialization is experimental and may work differently in future versions')
		return obj.item()
	return obj
```
It largely rips the appropriate information using the calls we already know about. I noticed while reading the code that they also have a pandas encoder. Thought it would be cool to add it.

**Pandas Encoder**

```py
def pandas_encode(obj, primitives=False):
	from pandas import DataFrame, Series
	if isinstance(obj, (DataFrame, Series)):
		#todo: this is experimental
		if not getattr(pandas_encode, '_warned', False):
			pandas_encode._warned = True
			warning('Pandas dumping support in json-tricks is experimental and may change in future versions.')
	if isinstance(obj, DataFrame):
		repr = hashodict()
		if not primitives:
			repr['__pandas_dataframe__'] = hashodict((
				('column_order', tuple(obj.columns.values)),
				('types', tuple(str(dt) for dt in obj.dtypes)),
			))
		repr['index'] = tuple(obj.index.values)
		for k, name in enumerate(obj.columns.values):
			repr[name] = tuple(obj.ix[:, k].values)
		return repr
	if isinstance(obj, Series):
		repr = hashodict()
		if not primitives:
			repr['__pandas_series__'] = hashodict((
				('name', str(obj.name)),
				('type', str(obj.dtype)),
			))
		repr['index'] = tuple(obj.index.values)
		repr['data'] = tuple(obj.values)
		return repr
	return obj


```

**Comment by ijl** [comment]
Oh, thanks. numpy is a good example in that the upstream doesn't have an approved way of representing it in JSON. I have no opinion on how it should be done and would not want to force an mplementation. I think you want to integrate any use of this library instead of json into json-tricks. For example, `return obj if USING_ORJSON else obj.tolist()` or the like to use native implementations for performance.
