### ISSUE TITLE
Publish crate for serde_json fork

### ISSUE THREAD

**Issue by opsengine** [ijl/orjson#76]
The code depends on a fork of serde_json. There is only one commit (9e9a959fce6075e90526bc3af4bde509a9af17dd) but it seems pretty important.
Would it be possible to publish the fork on crates.io under a new name i.e. serde_orjson or something? It would make it much easier to work with cargo vendor.
Thanks!

**Comment by ijl** [comment]
Do you clone the repo or download the source distribution from PyPI? I'd prefer to not publish the fork because it's not generally usable. It could be vendored into this repository or maturin could be modified to vendor everything.

**Comment by opsengine** [comment]
We clone the repo. That's ok though, we did a workaround so I'm closing the issue.

**Comment by ijl** [comment]
That's good. It needs to be solved in general still, and will be vendored into this repository and published after https://github.com/PyO3/maturin/pull/296.

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/2.6.8
