### ISSUE TITLE
orjson imports numpy at import time

### ISSUE THREAD

**Issue by wavenator** [ijl/orjson#78]
For some reason, importing `orjson` takes:
`CPU times: user 242 ms, sys: 441 ms, total: 682 ms
Wall time: 96.9 ms`

Now, after investigation with gdb, it looks like it importing `orjson` imports for some reason `numpy` as well. The issue is that importing numpy, not only takes a lot of time, but also opens multiple threads by using `openblas` for concurrency. I honestly don't know why orjson needs to import numpy during loading.

**Comment by ijl** [comment]
Ok, it imports lazily in 2.6.6.
