### ISSUE TITLE
separators argument support

### ISSUE THREAD

**Issue by simingy** [ijl/orjson#79]
```
TypeError: dumps() got an unexpected keyword argument: separators
```

tried to use `orjson` with `python-socketio` and it fails due to the above error.
is it possible to have 1-1 argument mapping support (such as `separators` argument) 
so we can reap the performance benefits without dealing with arg. translation?

Thanks

**Comment by ijl** [comment]
The libraries have incompatible APIs beyond the basic `dumps(obj)`. Maybe you could submit a patch to python-socketio to have configurable serializers.
