### ISSUE TITLE
pos in JSONDecodeError is 0

### ISSUE THREAD

**Issue by gredondogc** [ijl/orjson#81]
I'm using orjson 2.6.6, python 3.6 on Mac.

When trying to decode a badly encoded json a JSONDecodeError is raised but the exception does not have the correct position of the error.

For instance 

`e.__dict__`
returns:
```{
'msg': 'invalid escape at line 157 column 181',
 'doc': '',
 'pos': 0,
 'lineno': 1,
 'colno': 1}
```

Neither `pos`, `lineno` nor `colno` are correct.

**Comment by ijl** [comment]
Patches welcome. The data is on the serde error, it looks straight-forward.

**Comment by JMarkin** [comment]
@ijl 
I create pull request for this issue #151 
Check please.

**Comment by ijl** [comment]
https://github.com/ijl/orjson/releases/tag/3.5.3
