### ISSUE TITLE
Integer overflows

### ISSUE THREAD

**Issue by opsengine** [ijl/orjson#82]
There are two unchecked integer operation that can lead to an overflow. For one of them there is an input that triggers the overflow.

Overflow 1
```
thread '<unnamed>' panicked at 'attempt to add with overflow', serde_orjson-1.0.51/src/de.rs:787:38
```
This can be triggered with the code:
`orjson.loads("[65.356933999999967]")`

In `f64_from_parts()`:
`product_middle1=17707409016718886656`
`product_middle2=1020491046953003386`
and their sum exceeds 2^64.

Overflow 2
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', serde_orjson-1.0.51/src/de.rs:815:33
```

**Comment by ijl** [comment]
The overflow was correct and they have been modified to wrapping_* functions to not panic in debug. Fixed in 2.6.7.
