### ISSUE TITLE
option for tabulation (\n) indent ? 

### ISSUE THREAD

**Issue by guilbut** [ijl/orjson#84]
hello !

I'm looking to switch from simplejson to orjson. The problem is that I need to be able to have an option to have something readable with tabulation (\n) indent without increasing the size too much compared to a flat json. OPT_INDENT_2 is not a solution for me, because with deep nested objects, the double_space*indentation_level , increases too much the size of the json. Do you think you are going to add it ?

Thank you very much! |

**Comment by guilbut** [comment]
import json 
shopping_list = {"k":{"k":{"k":{"k":{"k":{"k":{"k":{"k":{"k":{"k":{"k":{"k":{"k":{"k":{"k":{"k":{"k":{"k":"value"}}}}}}}}}}}}}}}}}}
for indent in (2,'\t'):
    dumped = json.dumps(shopping_list,indent=indent)
    print("indent ",repr(indent), "-> size ", len(dumped))

give : 
indent  2 -> size  817
indent  '\t' -> size  493

**Comment by ijl** [comment]
That's interesting. I don't recall seeing a tab-indented JSON document personally. gzip is more likely to be used in my experience. It's too niche to support, sorry.
