### ISSUE TITLE
loads  with object_hook support ? 

### ISSUE THREAD

**Issue by guilbut** [ijl/orjson#85]
Hello !
I'm looking to switch from simplejson to orjson.
the orjson.dumps support "default" callback parameter,like the python standard json lib . But des orjson.loads does'nt support the "object_hook"callback parameter, making the use of "default" in order recreate the original object useless. Do you plan to support it ? 
thank you very much !

**Comment by ijl** [comment]
This library is scoped to just handling JSON well and I would suggest using another library for anything requiring validation.
