### ISSUE TITLE
RawJSON (like rapidjson) suport ? 

### ISSUE THREAD

**Issue by guilbut** [ijl/orjson#86]
Hello ! 
In order to be able to dumps with pretty indents and keep numpy.array in one line , I use rapidjson with RawJSON . Do you plan to suport something like that ? (but with bytes input)  
Thank  you very much for your amazing work  ! 
------------------------------------------------
import rapidjson
import numpy 

def default (obj):
    if isinstance (obj, numpy.ndarray):
        return rapidjson.RawJSON (rapidjson.dumps (obj.tolist ()))
    raise Exception(TypeError)

my_object = {"array1":numpy.array([1,2,3]),"array3": numpy.array([5,6,7])}
dumped = rapidjson.dumps(my_object,indent = 2,default = default )
print(dumped)

>>>
{
  "array1": [1,2,3],
  "array3": [5,6,7]
}

**Comment by ijl** [comment]
I think this is a niche use case requiring complexity that is beyond what I want to support, sorry.
