### ISSUE TITLE
Publish Windows bdist

### ISSUE THREAD

**Issue by frnkvieira** [ijl/orjson#9]
Hello :)
I'm quite interested to use this project on Vibora (https://github.com/vibora-io/vibora).
Do you have any plans to publish wheels to MacOS/Windows ? Maybe I can help with something ?
Thanks for the great work!

**Comment by ijl** [comment]
Ok, I intend to add them, and might get to it within a week. It's CI config that only I can do, but thanks.

**Comment by ijl** [comment]
macOS wheels were published in 2.0.0.

**Comment by ijl** [comment]
Windows wheels were published in 2.0.1.
