### ISSUE TITLE
Fallback to default function with option NON_STR_KEYS

### ISSUE THREAD

**Issue by ozankabak** [ijl/orjson#91]
When serializing dictionaries with non-string keys, the library throws an error if a key's type is not one of the supported types -- it does not try to serialize it via a call to `default`. This makes serializing dictionaries with key types such as `Decimal` (or other custom types) impossible. Is there a particular reason why the library does not attempt to call `default` before giving up in these cases? Note that the library does not behave like this uniformly; it does call `default` when a similar thing happens when dealing with `enum`s.

**Comment by ijl** [comment]
If you look into the details here and come up with a proposal we can discuss that but it will show there's complexity I don't have the time to catalog.
