### ISSUE TITLE
Support custom bidirectional de(serialization) with currently supported types

### ISSUE THREAD

**Issue by rwarren** [ijl/orjson#94]
Right now `orjson` serializes `datetime` to `str`, but cannot be configured to go in the reverse direction since the end result is just a `str`.

I would like to be able to configure `orjson` to work bidirectionally for numerous data types (including `datetime`), but A) don't have the appropriate hooks available, and B) can't override the way that `orjson` deals with types it supports automatically (like `datetime`).

For comparison, I can set up bidrectional (de)serialization of python `datetime` through `json` with the standard `json` module something like this:

```python
import datetime
import json
from typing import *

DT_KEY = ":__json__dt__:"

class MyEncoder(json.JSONEncoder):
    def default(self, o: Any) -> Any:
        if isinstance(o, datetime.datetime):
            return {DT_KEY: o.isoformat()}
        #return json.JSONEncoder.default(self, o)
        return super().default(o)

def object_hook(obj: Dict[str, Any]) -> Any:
    try:
        iso_date = obj[DT_KEY]
        return datetime.datetime.fromisoformat(iso_date)
    except:
        return obj

now = datetime.datetime.now()
dumped = json.dumps(now, cls = MyEncoder)
loaded = json.loads(dumped, object_hook = object_hook)
assert loaded == now
```

This is possible because of a few things:

1. `datetime.datetime` is obviously not supported by `json`, so a serialization hook is easy
2. The `object_hook` feature on `loads` allows for deserialization tricks like this for objects/dicts

Unless I'm missing something, the only option for partial satisfaction of what I want is to compose a wrapper class around my `datetime` objects and implement a default serializer for the wrapper class to get my custom "_datetime-in-a-dict_" storage encoding.  However, I see no possible way to get `orjson` to deserialize this directly to `datetime`, since there is no deserialization hook comparable to the `json` `object_hook` interception.

Regarding tricking `orjson` to encode `datetime` instances in other ways by wrapping it, this is ok for single instances, but much trickier for instances nested inside containers since they would all need to be found and wrapped in advance (vs being able to catch them directly at all levels via the default hook). Having to dive through containers to wrap all desired `datetime` (or whatever) objects in advance of serialization is obviously not ideal.

There are multiple ways `orjson` could hopefully deal with this, but here are a few suggestions that would be awesome if `orjson` could implement:

1. Add options to disable native `orjson` serialization for currently handled types
    * e.g. `OPT_DISABLE_DATETIME` to cause `datetime` objects to get routed through the default/custom serializer code (enabling custom serialization like my core `json` module code above)
    * Options for disabling/reimplementing each native type (like `OPT_DISABLE_NDARRAY`) would be excellent for similar reasons
2. Add an `object_hook` option for object/dict decoding, similar to what the `json` module has

**Comment by ijl** [comment]
There's `orjson.OPT_PASSTHROUGH_DATETIME` now. 

Deserializing to anything but basic types is not in scope for this library. That can be handled by libraries such as cattrs. There's more in https://github.com/ijl/orjson#questions.
