### ISSUE TITLE
Disable/override default datetime serialization

### ISSUE THREAD

**Issue by lbenc135** [ijl/orjson#96]
Hi, love your library. My colleagues and I would like to use it in our platform to speed up our serialization.

However, we have a strict date/datetime format we need to use, and I can't find a way to either override/disable your default datetime serialization, or alternatively specify a format.

Any help would be appreciated!

**Comment by ijl** [comment]
https://github.com/ijl/orjson#opt_passthrough_datetime in 3.1.0.
