### ISSUE TITLE
FEATURE: None/Null serialization option

### ISSUE THREAD

**Issue by Tetradeus** [ijl/orjson#97]
Hello,

It would be nice to have an option to not serialize fields which have null value.
What is your opinion ?

Thanks,

Tetra

**Comment by ijl** [comment]
I don't entirely understand what this would be or why it's desirable. But checking every attribute for null seems like a lot of complexity and a performance hit.

**Comment by clemensv** [comment]
@ijl I'd like to bring this back up. I'm having fairly wide, flat data structures (dataclasses) of 30+ fields that contain "sparse data" where only a few of those fields are set at any time. The data that I am encoding (ADS-B and Mode-S aircraft radio info) is delivering a mix of those fields across several kinds of records and I need a flat structure for stream processing.

An option that simply omits the null value entries would obviously save enormous bandwidth as I am sending > 1000 msg/sec of this kind from a single sender.  The option is fairly common in JSON serializers and I am surprised not to see it here.

```
{
                "ts": 1738065525087,
                "icao": "40799B",
                "df": 11,
                "tc": null,
                "bcode": null,
                "alt": null,
                "cs": null,
                "sq": null,
                "lat": null,
                "lon": null,
                "spd": null,
                "ang": null,
                "vr": null,
                "spd_type": null,
                "dir_src": null,
                "vr_src": null,
                "ws": null,
                "wd": null,
                "at": null,
                "ap": null,
                "hm": null,
                "roll": null,
                "trak": null,
                "gs": null,
                "tas": null,
                "hd": null,
                "ias": null,
                "m": null,
                "vrb": null,
                "vri": null,
                "rssi": -3.03,
                "emst": null,
                "tgt": null,
                "opst": null
            }
```
